### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by iterhating** [thygate/stable-diffusion-webui-depthmap-script#1]
First of, thanks for making this, it'll simplify the toolchain I worked out for this and keep things inside the WebUI.

I can't get it installed.

0. The installation directions could be amended to make more clear that the directories /repositories/midas will be made by the git clone command. I see now it's listed there, but I wasn't familiar with that name-as-create method of git cloning (I'm new to this, but I imagine others are too). Naively following the instructions had me making inside /scripts /repositories/midas/repositories/midas as a result of the git command, and then having to notice and fix the structure. I suggest changing to something like: 
"Clone the [MiDaS](https://github.com/isl-org/MiDaS) repository /scripts with command 
 `git clone https://github.com/isl-org/MiDaS.git repositories/midas`
This will download the repo to /scripts inside the necessary subfolders."

1. I think the imports on depthmap.py lines 18-21 should be ".repositories.midas...." with the integral period. Otherwise I get this error:
`(webSD_2) C:\SD\stable-diffusion\stable-diffusion-webui>python C:\SD\stable-diffusion\stable-diffusion-webui\webui.py --precision full --no-half --medvram
Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\SD\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 155, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\SD\stable-diffusion\stable-diffusion-webui\scripts\depthmap.py", line 18, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'repositories'`

2. With that change made, I get this error:
`(webSD_2) C:\SD\stable-diffusion\stable-diffusion-webui>python C:\SD\stable-diffusion\stable-diffusion-webui\webui.py --precision full --no-half --medvram
Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\SD\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 155, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\SD\stable-diffusion\stable-diffusion-webui\scripts\depthmap.py", line 18, in <module>
    from .repositories.midas.midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'depthmap'
`
So it still fails but it is possibly making the call into dpt_depth (though I'm not sure about that, no debugging print commands placed inside of dpt_depth print for me), perhaps the periods are not what are needed?

**Comment by thygate** [comment]
Hi, 

>This will download the repo to /scripts inside the necessary subfolders."

The midas repo should be in `/repositories`, only the `depthmap.py` script needs to be in `/scripts`

Run the git clone command from the `stable-diffusion-webui` directory.
This will clone the midas repo to `stable-diffusion-webui/repositories/` creating the directory `stable-diffusion-webui/repositories/midas/`.

I will update the install instructions to make this more clear.

**Comment by popedead** [comment]
hi, this is my error,, midas in repo, script in scripts

Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.54it/s]
DepthMap v0.1.0
device: cuda
Loading midas model weights ..
./models/midas/dpt_large-midas-2f21e586.pt
Error verifying pickled file from ./models/midas/dpt_large-midas-2f21e586.pt:
Traceback (most recent call last):
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\safe.py", line 76, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\safe.py", line 97, in load
    check_pt(filename)
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\safe.py", line 89, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error completing request
Arguments: ('city', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 1, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, 0, 0, True, True, False, 1, False, False, False, '', 1, '', 0, '', True, True, False, 1.0, 2.0, 'a painting in', 'style', 'picture frame, portrait photo', None) {}
Traceback (most recent call last):
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\txt2img.py", line 45, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\scripts.py", line 297, in run
    processed = script.run(p, *script_args)
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\scripts\depthmap.py", line 83, in run
    model = DPTDepthModel(
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 105, in __init__
    self.load(path)
  File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\repositories\midas\midas\base_model.py", line 13, in load
    if "optimizer" in parameters:
TypeError: argument of type 'NoneType' is not iterable

thanks
