### ISSUE TITLE
Unable to install ImportError: fontconfig not found

### ISSUE THREAD

**Issue by WuKaiYi** [thygate/stable-diffusion-webui-depthmap-script#103]
Traceback (most recent call last):
2023-02-05 03:39:48   File "/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
2023-02-05 03:39:48     script_module = script_loading.load_module(scriptfile.path)
2023-02-05 03:39:48   File "/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
2023-02-05 03:39:48     module_spec.loader.exec_module(module)
2023-02-05 03:39:48   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-02-05 03:39:48   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-02-05 03:39:48   File "/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 34, in <module>
2023-02-05 03:39:48     import vispy
2023-02-05 03:39:48   File "/usr/local/lib/python3.10/site-packages/vispy/__init__.py", line 27, in <module>
2023-02-05 03:39:48     from .util import config, set_log_level, keys, sys_info  # noqa
2023-02-05 03:39:48   File "/usr/local/lib/python3.10/site-packages/vispy/util/__init__.py", line 14, in <module>
2023-02-05 03:39:48     from . import fonts       # noqa
2023-02-05 03:39:48   File "/usr/local/lib/python3.10/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
2023-02-05 03:39:48     from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
2023-02-05 03:39:48   File "/usr/local/lib/python3.10/site-packages/vispy/util/fonts/_triage.py", line 11, in <module>
2023-02-05 03:39:48     from ._freetype import _load_glyph
2023-02-05 03:39:48   File "/usr/local/lib/python3.10/site-packages/vispy/util/fonts/_freetype.py", line 16, in <module>
2023-02-05 03:39:48     from ...ext.fontconfig import find_font
2023-02-05 03:39:48   File "/usr/local/lib/python3.10/site-packages/vispy/ext/fontconfig.py", line 12, in <module>
2023-02-05 03:39:48     raise ImportError('fontconfig not found')
2023-02-05 03:39:48 ImportError: fontconfig not found

When I try to install and restart the UI, it shows an error while loading

**Comment by qweryty** [comment]
I think this is just how vispy library works (here is the issue and a solution in their repo: https://github.com/vispy/vispy/issues/1556#issuecomment-1379480239).  

I was able to reproduce this bug using [AbdBarho/stable-diffusion-webui-docker](https://github.com/AbdBarho/stable-diffusion-webui-docker) and fixed it by installing `fontconfig`, `libglfw3-dev` and `libgles2-mesa-dev`

**Comment by cdhome** [comment]
using yum install fontconfig if you are centos

**Comment by cbolich** [comment]
> I think this is just how vispy library works (here is the issue and a solution in their repo: [vispy/vispy#1556 (comment)](https://github.com/vispy/vispy/issues/1556#issuecomment-1379480239)).
> 
> I was able to reproduce this bug using [AbdBarho/stable-diffusion-webui-docker](https://github.com/AbdBarho/stable-diffusion-webui-docker) and fixed it by installing `fontconfig`, `libglfw3-dev` and `libgles2-mesa-dev`

@qweryty I'm having trouble getting this to run in that same docker repo you are using.  Would you post your docker file?  I've been stuck on this and just can't get it to work

**Comment by ac2522** [comment]
Yo @cbolich did you get it to work?

**Comment by cbolich** [comment]
@ac2522 I'm still stuck getting EGL to load

I put the dependencies in the docker file, but still not quite able to get everything working.

**Comment by qweryty** [comment]
@cbolich I've created a fork with my changes
https://github.com/qweryty/stable-diffusion-webui-docker/blob/d54378ec745f67ffe8181430a6adafec7797e765/services/AUTOMATIC1111/Dockerfile#L41-L42

Although, you still need to reinstall the plugin after each docker repo update, since it looses all of the python dependencies.
