### ISSUE TITLE
Error loading script: depthmap.py

### ISSUE THREAD

**Issue by DennLie** [thygate/stable-diffusion-webui-depthmap-script#106]
What am i doing wrong?
Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\Users\***\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\***\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\***\stable-diffusion-webui\extensions\depthmap-script-thygate\scripts\depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'midas'

**Comment by DennLie** [comment]
Tried a couple things like installing timm and midas. Change the path like someone else recommended. deinstall and reinstall via auto1111. Solution was in the end that auto1111 install was somehow not working correctly. Downloading it manually and replace the extension in the stable-diffusion-webui\extensions folder fixed it for me.
