### ISSUE TITLE
new startup issue error loading depthmap.py

### ISSUE THREAD

**Issue by gsgoldma** [thygate/stable-diffusion-webui-depthmap-script#113]
Error loading script: depthmap.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "D:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "D:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "D:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

**Comment by lauridskern** [comment]
same error

**Comment by thygate** [comment]
force reinstall a recent version of timm

`pip install --force-reinstall timm==0.6.12`

**Comment by gsgoldma** [comment]
> pip install --force-reinstall timm==0.6.12

doing that broke my current install

**Comment by thygate** [comment]
can't help you if you don't give me any info

**Comment by gsgoldma** [comment]
> can't help you if you don't give me any info

My apologies. I forgot to capture the error log, and I deleted the venv for a fresh install. Next time I try it out, I'll capture the log.

**Comment by thygate** [comment]
The error message in the original post indicates you were using an old timm version that did not yet have the beit models.
The new midas models will not work without it, possibly another extension is still installing the old version.

**Comment by lintonxue00** [comment]
Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/drive/MyDrive/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/drive/MyDrive/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "/content/drive/MyDrive/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "/content/drive/MyDrive/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "/content/drive/MyDrive/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/backbones/beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

**Comment by Woisek** [comment]
Same here:

Error loading script: depthmap.py
Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "I:\Super SD 2.0\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

**Comment by jwvanderbeck** [comment]
My concern with the suggestion to force install timm 0.6.12 is that A1111 itself has a requirement defined as timm 0.4.12

How can two versions exist at the same time?
