### ISSUE TITLE
stderr: ERROR: while installing extesnion

### ISSUE THREAD

**Issue by runner22k** [thygate/stable-diffusion-webui-depthmap-script#117]
I tried to install this script just now and I got below error. which package did it fail to install?

```
stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\stable-diffusion-webui\\venv\\Lib\\site-packages\\~il\\_imaging.cp310-win_amd64.pyd'
Check the permissions.
```

**And this too**
```

Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 54, in <module>
    from inpaint.mesh import write_ply, read_ply, output_3d_photo
  File "C:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh.py", line 25, in <module>
    from inpaint.mesh_tools import get_depth_from_maps, get_map_from_ccs, get_edge_from_nodes, get_depth_from_nodes, get_rgb_from_nodes, crop_maps_by_size, convert2tensor, recursive_add_edge, update_info, filter_edge, relabel_node, depth_inpainting
  File "C:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh_tools.py", line 33, in <module>
    import transforms3d
ModuleNotFoundError: No module named 'transforms3d'
```

**Comment by runner22k** [comment]
Solved. We should close and exit Web UI completely. only then it is showing up without any errors.
