### ISSUE TITLE
ModuleNotFoundError: No module named 'midas'

### ISSUE THREAD

**Issue by Mozoloa** [thygate/stable-diffusion-webui-depthmap-script#128]
Hello!

I've just installed this extension via URL in an updated perfectly functioning A1111 install and the script won't load.

At launch I get `ModuleNotFoundError: No module named 'midas'`

More info:

```
Launching Web UI with arguments: --autolaunch --xformers --ckpt-dir C:\AI\Models\Stable-diffusion --vae-path C:\AI\Models\Stable-diffusion\NewVAE.vae.pt --embeddings-dir C:\AI\Models\Embeddings
Error loading script: depthmap.py
Traceback (most recent call last):
  File "D:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\Depth\scripts\depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'midas'
```

I've tried deleting venv, and it's still doing it

**Comment by Itelmen** [comment]
Just rename the script folder from "DepthMap" to "stable-diffusion-webui-depthmap-script". This is in "stable-diffusion-webui\extensions\"

**Comment by Mozoloa** [comment]
This worked ! That's odd that the folder was renamed that way and it broke things

**Comment by Xyem** [comment]
Of the 36 extensions I have installed, only this one and `sd_smartprocess` seem to be sensitive to the name of their directory.

In this case, I suspect it is because it is hard-coded here: https://github.com/thygate/stable-diffusion-webui-depthmap-script/blob/main/scripts/depthmap.py#L37

**Comment by Mozoloa** [comment]
> Of the 36 extensions I have installed, only this one and `sd_smartprocess` seem to be sensitive to the name of their directory.
> 
> In this case, I suspect it is because it is hard-coded here: https://github.com/thygate/stable-diffusion-webui-depthmap-script/blob/main/scripts/depthmap.py#L37

And that's exactly one line above the error, good find

**Comment by Xyem** [comment]
Replacing that line with the following appears to work:

```
import pathlib
path_append = pathlib.Path(__file__).parent.resolve()
sys.path.append(str(path_append))
```

**Comment by thygate** [comment]
> Replacing that line with the following appears to work:
> 
> ```
> import pathlib
> path_append = pathlib.Path(__file__).parent.resolve()
> sys.path.append(str(path_append))
> ```

will change in next version
