### ISSUE TITLE
Script not showing up - Please help

### ISSUE THREAD

**Issue by razmile80** [thygate/stable-diffusion-webui-depthmap-script#134]
Hey! I am fairy new to stable diffusion world and I try to make sense of everything. I've respected all the installing steps but for some reason I can't make depth map to work. Check below:

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\Users\chitu\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\chitu\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\chitu\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 54, in <module>
    from inpaint.mesh import write_ply, read_ply, output_3d_photo
  File "C:\Users\chitu\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh.py", line 22, in <module>
    from inpaint.utils import path_planning, open_small_mask, clean_far_edge, refine_depth_around_edge
  File "C:\Users\chitu\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\utils.py", line 18, in <module>
    from skimage.feature import canny
  File "C:\Users\chitu\stable-diffusion-webui\venv\lib\site-packages\skimage\feature\__init__.py", line 4, in <module>
    from ._cascade import Cascade
ImportError: DLL load failed while importing _cascade: The specified module could not be found.

Thanks!

**Comment by thygate** [comment]
I googled around, and some similar issues with skimage were solved by installing the  Microsoft Visual C++ Redistributable for Visual Studio : https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by kiyasov** [comment]
Solution for Mac

`brew install ffmpeg`

**Comment by razmile80** [comment]
Thank you both. I could make it work later the same day by simply closing and opening SD probably for 2 times and anytime I have opened it it have downloaded more and more probably essential files.

**Comment by xaviersykora** [comment]
Restarting the webUI solved the issue for me. It downloaded requirements upon opening that it had not installed when providing the link for webUI to install it in the extensions tab.
