### ISSUE TITLE
Error loading script: depthmap.py

### ISSUE THREAD

**Issue by timo-tain** [thygate/stable-diffusion-webui-depthmap-script#137]
> Error loading script: depthmap.py
> Traceback (most recent call last):
>   File "/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
>     script_module = script_loading.load_module(scriptfile.path)
>   File "/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 14, in <module>
>     from numba import njit, prange
>   File "/usr/local/lib/python3.10/site-packages/numba/__init__.py", line 42, in <module>
>     from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
>   File "/usr/local/lib/python3.10/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
>     from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
>   File "/usr/local/lib/python3.10/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
>     from numba.np.ufunc import _internal
> SystemError: initialization of _internal failed without raising an exception

I am using Docker to run AUTOMATIC1111, I wonder if there is a connection?

**Comment by potesd** [comment]
I just had this happen on a fresh install, and just had to close the Command prompt or terminal window and restart the WebUI. After installing the script, it adds the requirements to your next launch of the webUI.

**Comment by bbecausereasonss** [comment]
Having this issue in Win11.

Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 42, in <module>
    from dmidas.dpt_depth import DPTDepthModel
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\dmidas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\dmidas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\dmidas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

**Comment by chimeK** [comment]
Have This issue on MacBook M1

Restarting UI...
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Error loading script: depthmap.py
Traceback (most recent call last):
  File "/Users/chimekuan/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/chimekuan/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/chimekuan/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 58, in <module>
    from inpaint.mesh import write_mesh, read_mesh, output_3d_photo
  File "/Users/chimekuan/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/inpaint/mesh.py", line 16, in <module>
    from moviepy.editor import ImageSequenceClip
  File "/Users/chimekuan/.pyenv/versions/3.10.6/lib/python3.10/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Users/chimekuan/.pyenv/versions/3.10.6/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/Users/chimekuan/.pyenv/versions/3.10.6/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/Users/chimekuan/.pyenv/versions/3.10.6/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/Users/chimekuan/.pyenv/versions/3.10.6/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Users/chimekuan/.pyenv/versions/3.10.6/lib/python3.10/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Users/chimekuan/.pyenv/versions/3.10.6/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 173, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Users/chimekuan/.pyenv/versions/3.10.6/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 33, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

**Comment by thygate** [comment]
@chimeK This is not related to this issue, why post here ?

You need to use brew to install ffmpeg, this has come up before, ..

Solution : https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/118#issuecomment-1465276686

Please use search first to see if it has come up before.

**Comment by chimeK** [comment]
hank you for your response. I didn't carefully search for related posts at that time, which is why I posted here. I will delete the post later.

**Comment by thygate** [comment]
No problem, you don't have to delete anything, it's fine. Did you get it working ?

**Comment by braintm** [comment]
Hello. I have the same problem. The solution from the link does not work.

**Comment by thygate** [comment]
> Hello. I have the same problem. The solution from the link does not work. Starting from the first point, explanations are already needed.

>Error loading script: depthmap.py

Several people have posted in this thread with completely different issues. 

Specify your problem, what platform you're running on, and what you're trying to do.

If you get an error, post the complete error message !

**Comment by braintm** [comment]
Same issue as here https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/137#issuecomment-1501235744

**Comment by thygate** [comment]
@braintm 

If you don't post the stack trace I can't be sure you're having the same issue.

The missing beit models in timm can have several reasons.

Deforum is known to cause conflicts because it installs an older version of timm that did not yet include the beit models.
