### ISSUE TITLE
Could not open mesh. Can't generate video.

### ISSUE THREAD

**Issue by shdxtor** [thygate/stable-diffusion-webui-depthmap-script#153]
Hi! does anyone know how to fix this problem? I get this is every time when I press "Generate Video" button.

Error completing request
Arguments: ('', '300', '40', 1, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', False, 0, 2) {}
Traceback (most recent call last):
  File "L:\stable-diffusion-true\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "L:\stable-diffusion-true\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "L:\stable-diffusion-true\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 805, in run_makevideo
    raise Exception("Could not open mesh.")
Exception: Could not open mesh.

**Comment by shdxtor** [comment]
Resolved) forgot to press checkbox - Generate 3D inpainted mesh. (Sloooow)

**Comment by LilChrisHe** [comment]
same here even I pressed the checkbox
