### ISSUE TITLE
Error loading scipt depthmap.py

### ISSUE THREAD

**Issue by Gotobuild** [thygate/stable-diffusion-webui-depthmap-script#154]
Error loading script: depthmap.py
Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 54, in <module>
    from inpaint.mesh import write_ply, read_ply, output_3d_photo
  File "D:\StableDiffusion\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh.py", line 16, in <module>
    from moviepy.editor import ImageSequenceClip
ModuleNotFoundError: No module named 'moviepy'

I use stable diffusion extension to install depthmap, but when after I apply and restart, it shows failed to load scipt. I know that I need to put moviepy in somewhere, but I not sure how to fix this. Really appreciate if anyone can help me.

**Comment by thygate** [comment]
Just restart the backend and it should auto install all the requirements.

**Comment by edwinzeng2005** [comment]
I have the same error and after restarting the UI, the depth tab still does not appear.
`Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/backbones/beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'`

**Comment by thygate** [comment]
> I have a similar error and after restarting the UI, the depth tab still does not appear.
> 
> `Error loading script: depthmap.py Traceback (most recent call last): File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module module_spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 40, in <module> from midas.dpt_depth import DPTDepthModel File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/dpt_depth.py", line 5, in <module> from .blocks import ( File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/blocks.py", line 4, in <module> from .backbones.beit import ( File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/backbones/beit.py", line 9, in <module> from timm.models.beit import gen_relative_position_index ModuleNotFoundError: No module named 'timm.models.beit'`

>No module named 'timm.models.beit'`

This is a different issue. Sounds like another possible conflict with another midas source folder..
What other extensions do you have active ? Try disabling other extensions to see if that works ..

**Comment by edwinzeng2005** [comment]
> This is a different issue. Sounds like another possible conflict with another midas source folder.. What other extensions do you have active ? Try disabling other extensions to see if that works ..

I am using Nolan's script for Colab. The other extensions are the webui tunnels, control-net, openpose, images-browser, and tagcomplete.

`!git clone https://github.com/nolanaatama/sd-webui-tunnels /content/stable-diffusion-webui/extensions/sd-webui-tunnels
!git clone https://github.com/Mikubill/sd-webui-controlnet /content/stable-diffusion-webui/extensions/sd-webui-controlnet
!git clone https://github.com/fkunn1326/openpose-editor /content/stable-diffusion-webui/extensions/openpose-editor
!git clone https://github.com/yfszzx/stable-diffusion-webui-images-browser /content/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser
!git clone https://github.com/DominikDoom/a1111-sd-webui-tagcomplete /content/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete
`

**Comment by thygate** [comment]
> > This is a different issue. Sounds like another possible conflict with another midas source folder.. What other extensions do you have active ? Try disabling other extensions to see if that works ..
> 
> I am using Nolan's script for Colab. The other extensions are the webui tunnels, control-net, openpose, images-browser, and tagcomplete.
> 
> `!git clone https://github.com/nolanaatama/sd-webui-tunnels /content/stable-diffusion-webui/extensions/sd-webui-tunnels !git clone https://github.com/Mikubill/sd-webui-controlnet /content/stable-diffusion-webui/extensions/sd-webui-controlnet !git clone https://github.com/fkunn1326/openpose-editor /content/stable-diffusion-webui/extensions/openpose-editor !git clone https://github.com/yfszzx/stable-diffusion-webui-images-browser /content/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser !git clone https://github.com/DominikDoom/a1111-sd-webui-tagcomplete /content/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete `

I was a bit fast to jump to conclusions, there has been a problem with another extension using an older version of midas that did not yet use the beit model.

>No module named 'timm.models.beit'

Here it seems to be an issue with timm, this has come up several times when running on colab, please check the other colab issue reports for possible solutions, like reinstalling the correct version of timm.

**Comment by edwinzeng2005** [comment]
Ok I have resolved the missing timm module and midas files.

After restarting the web-ui, I am getting the following errors. The depth tab still didn't show.
`Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 39, in <module>
    from stereoimage_generation import apply_stereo_divergence, overlap_red_cyan
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/stereoimage_generation.py", line 29
    match mode:
          ^
SyntaxError: invalid syntax

Error loading script: stereoimage_generation.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/stereoimage_generation.py", line 29
    match mode:
          ^
SyntaxError: invalid syntax`

**Comment by thygate** [comment]
The match/case syntax, otherwise known as Structural Pattern Matching, was only [introduced in Python version 3.10](https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching).

You can update to python 3.10, or ..

You can remove that whole function (create_stereoimage) (line 5 to 42) from the file (stereoimage_generation.py), it is no longer used in the latest version.

**Comment by Gotobuild** [comment]
> Just restart the backend and it should auto install all the requirements.

Thank you for your help, but when I restarted the backend, it shows Installing all requirements for the WEBUI like usual. But it stuck at this step for really longtime. I know my cmd wasi going to install required package in your file, but it seems that my stable diffusion webui cannot install it automatically. Do you know how to fix this? Appreciate
