### ISSUE TITLE
(Error completing request) how do i fix this 

### ISSUE THREAD

**Issue by joosun1** [thygate/stable-diffusion-webui-depthmap-script#166]
0%|                                                                                            | 0/1 [11:49<?, ?it/s]
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=1200x1600 at 0x17AFFBDAA70>, None, '', '', 1, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, True, True, True, True, True, True, 2.5, 'polylines_sharp', 0, False, False, False, False, False, 'u2net', False, 0, 2, False, None, True) {}
Traceback (most recent call last):
  File "C:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1069, in run_generate
    outputs, mesh_fi = run_depthmap(
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 573, in run_depthmap
    images.save_image(Image.fromarray(img_output), path=outpath, basename=basename, seed=None, prompt=None, extension=opts.samples_format, info=info, short_filename=True,no_prompt=True, grid=False, pnginfo_section_name="extras", existing_info=None, forced_filename=None)
  File "C:\stable-diffusion\stable-diffusion-webui\modules\images.py", line 595, in save_image
    image = image.resize((round(image.width * opts.target_side_length / image.height), round(opts.target_side_length)), LANCZOS)
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2192, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: image has wrong mode

Traceback (most recent call last):
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

**Comment by thygate** [comment]
>ValueError: image has wrong mode

It seems it is unable to save the 16bit png image..

What generation parameters ?
Does it work on other files ?

Does it work when disabling "Save Png", does the returned depthmap in the webui look ok ?

**Comment by checksummaster** [comment]
Disable jpeg work for me, thank
