### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by muriellla** [thygate/stable-diffusion-webui-depthmap-script#170]
hello, I downloaded automatic 1111 and the depth map extension yesterday but I can't create a depth map, my terminal is always showing this issue: 

FileNotFoundError: [Errno 2] No such file or directory: "<div class='error'>UnboundLocalError: local variable &#x27;inpaint_imgs&#x27; referenced before assignment</div><div class='performance'><p class='time'>Time taken: <wbr>0.81s</p></div>"

Maybe someone can help me. 
thanks in advance

**Comment by muriellla** [comment]
Sorry, I am super new to the topic ud did not know what all is needed. I run the script in my Terminal (Mac iOS) and the image I used was am AI generated image I downloaded from Dall-E (png).


DepthMap v0.3.11
device: cpu
Loading model weights from  ./models/leres/res101.pth
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=1024x1024 at 0x2AAB3D990>, None, '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, True, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "/Users/C/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/C/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/C/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1110, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "/Users/C/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 712, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
UnboundLocalError: local variable 'inpaint_imgs' referenced before assignment

Traceback (most recent call last):
  File "/Users/C/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/C/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/C/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Users/C/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "/Users/C/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/Users/C/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: "<div class='error'>UnboundLocalError: local variable &#x27;inpaint_imgs&#x27; referenced before assignment</div><div class='performance'><p class='time'>Time taken: <wbr>0.89s</p></div>"

**Comment by muriellla** [comment]
I hav found the problem. Thank you!

**Comment by ytnurg** [comment]
what was the problem?
