### ISSUE TITLE
Installed in Stable Diffusion but not running

### ISSUE THREAD

**Issue by dodolfo** [thygate/stable-diffusion-webui-depthmap-script#180]
Hi there!
I could install this script in Stable Diffusion. However, when I hit Apply and Restart UI, in the console, it shows me the next:

Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\Users\Dodolfo\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Dodolfo\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Dodolfo\stable-diffusion-webui\extensions\Depth Map\scripts\depthmap.py", line 39, in <module>
    from stereoimage_generation import create_stereoimages
ModuleNotFoundError: No module named 'stereoimage_generation'

What am I doing wrong?

**Comment by thygate** [comment]
did you restart the backend ?

**Comment by dodolfo** [comment]
Hi! Sorry for delay
Which backend do you mean?

**Comment by dodolfo** [comment]
I'm trying but nothing happens. It still doesn't display the Depth option on Stable Diffusion.

**Comment by thygate** [comment]
>C:\Users\Dodolfo\stable-diffusion-webui\extensions\Depth Map\scripts\depthmap.py
>\Depth Map\

you need to install with the default path name, delete the folder and reinstall with default name, or rename the folder to the default name and restart the backend.

default name is `stable-diffusion-webui-depthmap-script`

**Comment by dodolfo** [comment]
Now it works!
Thank you very much! :)

**Comment by thygate** [comment]
you're welcome, enjoy!
