### ISSUE TITLE
FileNotFoundError Compute on GPU

### ISSUE THREAD

**Issue by RedRubyOwl** [thygate/stable-diffusion-webui-depthmap-script#184]
Hello,

when I try to generate with GPU it always shows this issue:

"FileNotFoundError: [Errno 2]"

Full stack trace

"DepthMap v0.3.11
device: cuda
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

wholeImage being processed in : 896
Adjust factor is: 2.2786458333333335
Selecting patches ...
Target resolution:  (2723, 4083, 3)
Resulting depthmap resolution will be : (2048, 3071)
patches to process: 35
         processing patch 0 / 34 | [ 162  162 1865 1865]
         processing patch 1 / 34 | [ 415  162 1865 1865]
         processing patch 2 / 34 | [ 668  162 1865 1865]
         processing patch 3 / 34 | [ 921  162 1865 1865]
         processing patch 4 / 34 | [1173  162 1865 1865]
         processing patch 5 / 34 | [  18   18 1649 1649]
         processing patch 6 / 34 | [  18  271 1649 1649]
         processing patch 7 / 34 | [ 271   18 1649 1649]
         processing patch 8 / 34 | [ 523   18 1649 1649]
         processing patch 9 / 34 | [ 776   18 1649 1649]
         processing patch 10 / 34 | [1029   18 1649 1649]
         processing patch 11 / 34 | [1282   18 1649 1649]
         processing patch 12 / 34 | [ 153  659 1378 1378]
         processing patch 13 / 34 | [ 406  659 1378 1378]
         processing patch 14 / 34 | [ 659  659 1378 1378]
         processing patch 15 / 34 | [ 912  659 1378 1378]
         processing patch 16 / 34 | [1164  659 1378 1378]
         processing patch 17 / 34 | [1417  659 1378 1378]
         processing patch 18 / 34 | [1724  713 1270 1270]
         processing patch 19 / 34 | [1751  487 1215 1215]
         processing patch 20 / 34 | [   9  262 1161 1161]
         processing patch 21 / 34 | [   9  514 1161 1161]
         processing patch 22 / 34 | [   9  767 1161 1161]
         processing patch 23 / 34 | [ 262    9 1161 1161]
         processing patch 24 / 34 | [ 514    9 1161 1161]
         processing patch 25 / 34 | [ 767    9 1161 1161]
         processing patch 26 / 34 | [1020    9 1161 1161]
         processing patch 27 / 34 | [1273    9 1161 1161]
         processing patch 28 / 34 | [ 144 1155  891  891]
         processing patch 29 / 34 | [ 903 1155  891  891]
         processing patch 30 / 34 | [1155 1155  891  891]
         processing patch 31 / 34 | [1408 1155  891  891]
         processing patch 32 / 34 | [1661 1155  891  891]
         processing patch 33 / 34 | [1913 1155  891  891]
         processing patch 34 / 34 | [   0 1011  674  674]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:30<00:00, 30.59s/it]
Done.
Running 3D Photo Inpainting ..
Loading edge model ..
Loading depth model ..
Loading rgb model ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Generating inpainted mesh .. (go make some coffee) ..
  0%|                                                                                            | 0/1 [05:30<?, ?it/s]
Error completing request4%|████████▋                                                    | 1/7 [02:47<16:42, 167.01s/it]
Arguments: (0, <PIL.Image.Image image mode=RGB size=3072x2048 at 0x20717470520>, None, '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, True, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\c\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 766, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
  File "C:\Users\c\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 920, in run_3dphoto
    rt_info = write_mesh(img,
  File "C:\Users\c\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh.py", line 1895, in write_mesh
    info_on_pix, input_mesh, image, depth, edge_ccs = extrapolate(input_mesh, info_on_pix, image, depth, other_edge_with_id, edge_map, edge_ccs,
  File "C:\Users\c\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh_tools.py", line 205, in extrapolate
    depth_edge_output = depth_edge_model.forward_3P(t_mask, t_context, t_rgb, t_disp, t_edge, unit_length=128,
  File "C:\Users\c\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\networks.py", line 311, in forward_3P
    edge_output = self.forward(enlarge_input)
  File "C:\Users\c\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\networks.py", line 324, in forward
    x6 = self.decoder_1(torch.cat((x5, x2), dim=1))
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 956, in forward
    return F.conv_transpose2d(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 6.00 GiB total capacity; 3.97 GiB already allocated; 0 bytes free; 4.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\c\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\c\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\c\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1171, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "C:\Users\c\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 771, in run_depthmap
    shared.sd_model.first_stage_model.to(devices.device)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 54, in to
    return super().to(*args, **kwargs)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.27 GiB already allocated; 0 bytes free; 4.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Extrapolating border:  14%|████████▋                                                    | 1/7 [04:21<26:07, 261.32s/it]
Traceback (most recent call last):
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\c\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: "<div class='error'>OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.27 GiB already allocated; 0 bytes free; 4.28 GiB reserved in total by PyTorch) If reserved memory is &gt;&gt; allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF</div><div class='performance'><p class='time'>Time taken: <wbr>6m 9.05s</p><p class='vram'>Torch active/reserved: 4374/4380 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"

selections:
Generate 3D inpainted mesh 
Generate 4 demo videos with 3D inpainted mesh
BOOST (multi-resolution merging)
Save DepthMap
Show DepthMap

Hope someone can help me.
many thanks in advance

**Comment by HanshustlerHHHH** [comment]
i got the same error :( 

Traceback (most recent call last):
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: "<div class='error'>OutOfMemoryError: CUDA out of memory. Tried to allocate 342.00 MiB (GPU 0; 6.00 GiB total capacity; 4.21 GiB already allocated; 0 bytes free; 5.12 GiB reserved in total by PyTorch) If reserved memory is &gt;&gt; allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF</div><div class='performance'><p class='time'>Time taken: <wbr>28m 10.14s</p><p class='vram'>Torch active/reserved: 4716/5252 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"

**Comment by thygate** [comment]
You can compute on CPU if you don't have enough GPU memory, it will just be a bit slower.

**Comment by MrJiaTu** [comment]
I had a similar problem,
FileNotFoundError: [Errno 2] No such file or directory: "<div class='error'>OutOfMemoryError: CUDA out of memory. Tried to allocate 516.00 MiB (GPU 0; 12.00 GiB total capacity; 3.36 GiB already allocated; 6.62 GiB free; 3.39 GiB reserved in total by PyTorch) If reserved memory is &gt;&gt; allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF</div><div class='performance'><p class='time'>Time taken: <wbr>1m 44.30s</p><p class='vram'>Torch active/reserved: 4736/6964 MiB, <wbr>Sys VRAM: 8993/12288 MiB (73.19%)</p></div>"
It shows that I'm not running out of memory on the GPU
Hope someone can help me.
many thanks in advance

**Comment by thygate** [comment]
The 

>FileNotFoundError

is the secondary error, occurring because of the first error : 

>OutOfMemoryError: CUDA out of memory
