### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Checkmate** [thygate/stable-diffusion-webui-depthmap-script#190]
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x24EA5BD8190>, None, '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, False, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "C:\workspace\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 836, in run_3dphoto
    depth_feat_weight = torch.load(depthmodel_path, map_location=torch.device(device))
  File "C:\workspace\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "C:\workspace\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\workspace\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\workspace\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 2282994 more bytes. The file might be corrupted.

**Comment by thygate** [comment]
>RuntimeError: unexpected EOF, expected 2282994 more bytes. The file might be corrupted.

Not a bug, your downloaded models are corrupted, delete models in /models/3dphoto and try again, and don't interrupt the download.
