### ISSUE TITLE
Problems with installing the script

### ISSUE THREAD

**Issue by Five-Birds** [thygate/stable-diffusion-webui-depthmap-script#191]
I tried to install the script but in the cmd prompt i got the following error message and do not see the script or the depth tab:

Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\Users\Five-\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Five-\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Five-\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 58, in <module>
    from inpaint.mesh import write_mesh, read_mesh, output_3d_photo
  File "C:\Users\Five-\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh.py", line 16, in <module>
    from moviepy.editor import ImageSequenceClip
ModuleNotFoundError: No module named 'moviepy'

Is there a solution for that or what i am doing wrong ?

**Comment by Five-Birds** [comment]
I had the wrong python version installed, after deinstalling python 3.10.11 and reinstalling 3.10.6 it now seems to work

**Comment by Five-Birds** [comment]
Topic closed
