### ISSUE TITLE
.PIL.Image.Image Issue

### ISSUE THREAD

**Issue by ytnurg** [thygate/stable-diffusion-webui-depthmap-script#197]
after disabling this and save as png..
![image](https://user-images.githubusercontent.com/125344199/234580943-e3367bb4-6f93-41ca-bd96-1412a8ac0665.png)
I get this error... new to all this, if it could be explained simply in lay man's terms I would appreciate it. Running stable diffusion 1.5 from camenduru github on google collab. Currently out of tokens on my collab pro account... is that my issue? After updating and restarting WebUI I go to the Depth tab and generate the video in cpu mode no boost, getting this:

Closing server running on port: 7860
Restarting UI...
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
ControlNet v1.1.112
all detected, remote.moe trying to connect...
Warning: Permanently added the RSA host key for IP address '54.161.197.247' to the list of known hosts.
all detected, cloudflared trying to connect...
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
Public WebUI Colab URL: http://wa6luxd3lds6xtxfb775tcfyfpddollhksadpamkwjppyby5irya.remote.moe 
Public WebUI Colab URL: https://f8674afc-4f25-4d13.gradio.live 
Public WebUI Colab URL: https://ff7e1e0e93e851.lhr.life
Public WebUI Colab URL: https://logs-arthur-shine-analysis.trycloudflare.com
Startup time: 27.8s (load scripts: 13.2s, create ui: 14.5s, gradio launch: 0.1s).

DepthMap v0.3.11
device: cpu
Loading model weights from  ./models/leres/res101.pth
Downloading https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download to ./models/leres/res101.pth
100% 506M/506M [00:49<00:00, 10.8MB/s]
Computing depthmap(s) ..
  0% 0/1 [00:00<?, ?it/s]

Generating (occluded) mesh ..
100% 1/1 [00:08<00:00,  8.47s/it]
Done.
Running 3D Photo Inpainting .. 
Downloading https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth to ./models/3dphoto/edge_model.pth
100% 43.8M/43.8M [00:03<00:00, 14.0MB/s]
Downloading https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/depth-model.pth to ./models/3dphoto/depth_model.pth
100% 197M/197M [00:22<00:00, 9.35MB/s]
Downloading https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/color-model.pth to ./models/3dphoto/color_model.pth
100% 197M/197M [00:25<00:00, 8.01MB/s]
Loading edge model ..
Loading depth model ..
Loading rgb model ..
  0% 0/1 [00:00<?, ?it/s]
Generating inpainted mesh .. (go make some coffee) ..

  0% 0/7 [00:00<?, ?it/s]
Creating mesh:   0% 0/7 [00:00<?, ?it/s]
Creating mesh:  14% 1/7 [00:12<01:15, 12.64s/it]
Extrapolating border:  14% 1/7 [00:12<01:15, 12.64s/it]
Extrapolating border:  29% 2/7 [01:03<02:55, 35.06s/it]
Context and holes:  29% 2/7 [01:03<02:55, 35.06s/it]   
Context and holes:  43% 3/7 [01:43<02:29, 37.39s/it]
Inpaint 1:  43% 3/7 [01:43<02:29, 37.39s/it]        
Inpaint 1:  57% 4/7 [04:28<04:23, 87.70s/it]
Inpaint 2:  57% 4/7 [04:28<04:23, 87.70s/it]
Inpaint 2:  71% 5/7 [04:43<02:02, 61.47s/it]
Reproject mesh:  71% 5/7 [04:43<02:02, 61.47s/it]
Reproject mesh:  86% 6/7 [04:50<00:43, 43.11s/it]
Generating faces:  86% 6/7 [04:50<00:43, 43.11s/it]
Generating faces: 100% 7/7 [04:55<00:00, 42.17s/it]
Writing mesh file outputs/extras-images/depthmap-0000.obj ...

  0% 0/2891920 [00:00<?, ?it/s]
Saving vertices:   0% 0/2891920 [00:00<?, ?it/s]
Saving vertices:   1% 22909/2891920 [00:00<00:12, 229083.12it/s]
Saving vertices:   2% 46993/2891920 [00:00<00:12, 235993.35it/s]
Saving vertices:   2% 70593/2891920 [00:00<00:12, 230582.18it/s]
Saving vertices:   3% 94327/2891920 [00:00<00:11, 233209.08it/s]
Saving vertices:   4% 117661/2891920 [00:00<00:11, 232659.29it/s]
Saving vertices:   5% 140935/2891920 [00:00<00:11, 229417.70it/s]
Saving vertices:   6% 164365/2891920 [00:00<00:11, 230988.06it/s]
Saving vertices:   6% 187641/2891920 [00:00<00:11, 231543.79it/s]
Saving vertices:   7% 210803/2891920 [00:00<00:13, 199634.36it/s]
Saving vertices:   8% 231503/2891920 [00:01<00:15, 175873.99it/s]
Saving vertices:   9% 249989/2891920 [00:01<00:16, 155874.02it/s]
Saving vertices:   9% 266448/2891920 [00:01<00:18, 143403.11it/s]
Saving vertices:  10% 281428/2891920 [00:01<00:19, 137289.89it/s]
Saving vertices:  10% 295552/2891920 [00:01<00:19, 132157.72it/s]
Saving vertices:  11% 308999/2891920 [00:01<00:20, 128323.78it/s]
Saving vertices:  11% 321957/2891920 [00:01<00:20, 125235.04it/s]
Saving vertices:  12% 334541/2891920 [00:01<00:20, 123480.28it/s]
Saving vertices:  12% 347402/2891920 [00:02<00:20, 124866.51it/s]
Saving vertices:  12% 359922/2891920 [00:02<00:20, 124043.15it/s]
Saving vertices:  13% 372345/2891920 [00:02<00:20, 123886.34it/s]
Saving vertices:  13% 384855/2891920 [00:02<00:20, 124234.81it/s]
Saving vertices:  14% 397307/2891920 [00:02<00:20, 124317.74it/s]
Saving vertices:  14% 409746/2891920 [00:02<00:20, 122626.61it/s]
Saving vertices:  15% 423068/2891920 [00:02<00:19, 125727.45it/s]
Saving vertices:  15% 435779/2891920 [00:02<00:19, 126132.98it/s]
Saving vertices:  16% 448402/2891920 [00:02<00:19, 124075.96it/s]
Saving vertices:  16% 460822/2891920 [00:03<00:20, 118669.63it/s]
Saving vertices:  16% 473411/2891920 [00:03<00:20, 120736.90it/s]
Saving vertices:  17% 485530/2891920 [00:03<00:20, 118429.01it/s]
Saving vertices:  17% 498320/2891920 [00:03<00:19, 121164.21it/s]
Saving vertices:  18% 511120/2891920 [00:03<00:19, 123161.37it/s]
Saving vertices:  18% 524575/2891920 [00:03<00:18, 126513.81it/s]
Saving vertices:  19% 537533/2891920 [00:03<00:18, 127420.61it/s]
Saving vertices:  19% 550752/2891920 [00:03<00:18, 128835.69it/s]
Saving vertices:  19% 563651/2891920 [00:03<00:18, 128827.79it/s]
Saving vertices:  20% 576545/2891920 [00:03<00:17, 128726.17it/s]
Saving faces:  20% 581670/2891920 [00:03<00:17, 128726.17it/s]   
Saving faces:  21% 605410/2891920 [00:04<00:12, 176507.85it/s]
Saving faces:  22% 643529/2891920 [00:04<00:09, 237736.09it/s]
Saving faces:  24% 682814/2891920 [00:04<00:07, 284175.36it/s]
Saving faces:  25% 723568/2891920 [00:04<00:06, 321130.50it/s]
Saving faces:  26% 764285/2891920 [00:04<00:06, 346916.41it/s]
Saving faces:  28% 805561/2891920 [00:04<00:05, 366654.31it/s]
Saving faces:  29% 847767/2891920 [00:04<00:05, 383266.09it/s]
Saving faces:  31% 887669/2891920 [00:04<00:05, 387987.97it/s]
Saving faces:  32% 929618/2891920 [00:04<00:04, 397434.66it/s]
Saving faces:  34% 971238/2891920 [00:04<00:04, 403061.66it/s]
Saving faces:  35% 1012378/2891920 [00:05<00:04, 405560.06it/s]
Saving faces:  36% 1054160/2891920 [00:05<00:04, 409234.89it/s]
Saving faces:  38% 1095989/2891920 [00:05<00:04, 411949.59it/s]
Saving faces:  39% 1137186/2891920 [00:05<00:04, 406886.96it/s]
Saving faces:  41% 1179360/2891920 [00:05<00:04, 411302.85it/s]
Saving faces:  42% 1221769/2891920 [00:05<00:04, 415113.08it/s]
Saving faces:  44% 1263513/2891920 [00:05<00:03, 415807.10it/s]
Saving faces:  45% 1306641/2891920 [00:05<00:03, 420434.86it/s]
Saving faces:  47% 1349107/2891920 [00:05<00:03, 421698.66it/s]
Saving faces:  48% 1391283/2891920 [00:05<00:03, 416789.20it/s]
Saving faces:  50% 1432984/2891920 [00:06<00:03, 416852.29it/s]
Saving faces:  51% 1474681/2891920 [00:06<00:03, 410203.46it/s]
Saving faces:  52% 1515730/2891920 [00:06<00:03, 403597.28it/s]
Saving faces:  54% 1556124/2891920 [00:06<00:03, 398298.85it/s]
Saving faces:  55% 1597140/2891920 [00:06<00:03, 401766.32it/s]
Saving faces:  57% 1637346/2891920 [00:06<00:03, 400348.76it/s]
Saving faces:  58% 1680320/2891920 [00:06<00:02, 409030.50it/s]
Saving faces:  60% 1723199/2891920 [00:06<00:02, 414893.14it/s]
Saving faces:  61% 1765327/2891920 [00:06<00:02, 416793.53it/s]
Saving faces:  62% 1807354/2891920 [00:06<00:02, 417828.75it/s]
Saving faces:  64% 1850792/2891920 [00:07<00:02, 422775.39it/s]
Saving faces:  65% 1893081/2891920 [00:07<00:02, 414567.63it/s]
Saving faces:  67% 1936298/2891920 [00:07<00:02, 419765.33it/s]
Saving faces:  68% 1979834/2891920 [00:07<00:02, 424390.99it/s]
Saving faces:  70% 2022305/2891920 [00:07<00:02, 421927.99it/s]
Saving faces:  71% 2065833/2891920 [00:07<00:01, 425894.38it/s]
Saving faces:  73% 2109162/2891920 [00:07<00:01, 428096.72it/s]
Saving faces:  74% 2151988/2891920 [00:07<00:01, 419141.78it/s]
Saving faces:  76% 2195454/2891920 [00:07<00:01, 423710.43it/s]
Saving faces:  77% 2237868/2891920 [00:07<00:01, 422106.31it/s]
Saving faces:  79% 2280109/2891920 [00:08<00:01, 421691.55it/s]
Saving faces:  80% 2322343/2891920 [00:08<00:01, 421883.23it/s]
Saving faces:  82% 2365338/2891920 [00:08<00:01, 424286.07it/s]
Saving faces:  83% 2407779/2891920 [00:08<00:01, 421156.47it/s]
Saving faces:  85% 2451193/2891920 [00:08<00:01, 425016.30it/s]
Saving faces:  86% 2493707/2891920 [00:08<00:00, 423485.99it/s]
Saving faces:  88% 2536065/2891920 [00:08<00:00, 422141.11it/s]
Saving faces:  89% 2579228/2891920 [00:08<00:00, 424965.35it/s]
Saving faces:  91% 2622283/2891920 [00:08<00:00, 426632.37it/s]
Saving faces:  92% 2664952/2891920 [00:08<00:00, 421746.87it/s]
Saving faces:  94% 2707788/2891920 [00:09<00:00, 423708.37it/s]
Saving faces:  95% 2750172/2891920 [00:09<00:00, 422740.40it/s]
Saving faces:  97% 2792455/2891920 [00:09<00:00, 420739.88it/s]
Saving faces:  98% 2835852/2891920 [00:09<00:00, 424675.55it/s]
Saving faces: 100% 2891920/2891920 [00:09<00:00, 304114.42it/s]
  0% 0/1 [05:11<?, ?it/s]
All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x7F3F7F61CA00>, None, '', '', 1, 0, 512, 512, False, False, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, True, False, False, False, 'u2net', False, 0, 2, False, None, True, True, False, False) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1171, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 766, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 931, in run_3dphoto
    run_3dphoto_videos(mesh_fi, basename, outpath, 300, 40,
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 959, in run_3dphoto_videos
    vispy.use(app='egl')
  File "/usr/local/lib/python3.9/dist-packages/vispy/util/wrappers.py", line 93, in use
    use_app(app)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
  File "/usr/local/lib/python3.9/dist-packages/vispy/app/application.py", line 240, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "EGL":
Could not initialize

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: "<div class='error'>RuntimeError: Could not import backend &quot;EGL&quot;:\nCould not initialize</div><div class='performance'><p class='time'>Time taken: <wbr>7m 10.22s</p><p class='vram'>Torch active/reserved: 2065/2768 MiB, <wbr>Sys VRAM: 2887/15102 MiB (19.12%)</p></div>"

**Comment by thygate** [comment]
>RuntimeError: Could not import backend "EGL":\nCould not initialize

I cannot find a backend to render the videos, the mesh was saved successfully.

This has nothing to do with that JPEG setting. 
I have never ran it on colab, so I'm not sure what backend to use there.
Maybe try this one. https://github.com/hyqhyq3/stable-diffusion-webui-depthmap-script/commit/6573d7d4adaeb143ef99f86e03c251b06948c73e

>.PIL.Image.Image Issue

?

**Comment by ytnurg** [comment]
What I received after trying the extension you recommended in the camenduru colab stable diffusion. Still not completely working but I appreciate the progress! https://github.com/camenduru/stable-diffusion-webui-colab

All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x7FA10568DED0>, None, '', '', 1, 0, 512, 512, False, False, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, True, False, False, False, 'u2net', False, 0, 2, False, None, True, True, True, False) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1171, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 766, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 931, in run_3dphoto
    run_3dphoto_videos(mesh_fi, basename, outpath, 300, 40,
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 959, in run_3dphoto_videos
    vispy.use(app='jupyter_rfb')
  File "/usr/local/lib/python3.10/dist-packages/vispy/util/wrappers.py", line 93, in use
    use_app(app)
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/application.py", line 240, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "jupyter_rfb":
The jupyter_rfb backend relies on a the jupyter_rfb library: ``pip install jupyter_rfb``

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: "<div class='error'>RuntimeError: Could not import backend &quot;jupyter_rfb&quot;:\nThe jupyter_rfb backend relies on a the jupyter_rfb library: ``pip install jupyter_rfb``</div><div class='performance'><p class='time'>Time taken: <wbr>6m 21.05s</p><p class='vram'>Torch active/reserved: 2082/2768 MiB, <wbr>Sys VRAM: 2931/15102 MiB (19.41%)</p></div>"

**Comment by thygate** [comment]
jupyter_rfb is a remote framebuffer, if you want to use it you need to install it like it says.. pip install jupyter_rfb

**Comment by ytnurg** [comment]
Thank you again for all the aid my dude. I'm extremely new to all of this. Still haven't quite figured out how to remedy on collab yet, but getting closer after creating a few 'pip install' cells in the notebook and running them before running stable. trying to be descriptive incase others are having similar learning curve and problems. Also is there a better more easier way you recommend doing all of this? below is what I am currently running into any ideas?


All done.
Loading mesh ..
Generating videos ..
fov: 53.13010235415598
RFBOutputContext()
Error completing request
Arguments: ('outputs/extras-images/depthmap-0006.obj', '300', '40', 1, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', False, 1, 2) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1077, in run_makevideo
    fn_saved = run_3dphoto_videos(fn_mesh, basename, outpath, num_frames, num_fps, crop_border, vid_traj, x_shift_range, y_shift_range, z_shift_range, [''], dolly, fnExt, vid_ssaa)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1021, in run_3dphoto_videos
    normal_canvas, all_canvas, fn_saved = output_3d_photo(verts.copy(), colors.copy(), faces.copy(), copy.deepcopy(Height), copy.deepcopy(Width), copy.deepcopy(hFov), copy.deepcopy(vFov),
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/inpaint/mesh.py", line 2444, in output_3d_photo
    normal_canvas = Canvas_view(fov,
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/inpaint/mesh.py", line 2380, in __init__
    self.canvas = scene.SceneCanvas(bgcolor=bgcolor, size=(canvas_size*factor, canvas_size*factor))
  File "/usr/local/lib/python3.10/dist-packages/vispy/scene/canvas.py", line 135, in __init__
    super(SceneCanvas, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/canvas.py", line 211, in __init__
    self.create_native()
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/canvas.py", line 228, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/backends/_jupyter_rfb.py", line 82, in __init__
    self._loop = asyncio.get_event_loop()
  File "/usr/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'AnyIO worker thread'.

**Comment by ytnurg** [comment]
running amd processor thats why i went colab route

**Comment by thygate** [comment]
>RuntimeError: There is no current event loop in thread 'AnyIO worker thread'.

the rfb server is not running or no client is connected ? 
I'm just guessing here since I never used it and have no use for it ..

**Comment by thygate** [comment]
I cannot replicate this issue, no problems for me on latest a1111.

**Comment by graemeniedermayer** [comment]
Haha yes my "most recent version" was actually a version from last week. I double checked and I can' reproduce it with the most recent a1111.

**Comment by ytnurg** [comment]
still havent figured out how to make it work on colab, but I did get it to work with auto1111 with an amd processor!
