### ISSUE TITLE
ModuleNotFoundError: No module named 'vispy.visuals.text._sdf_cpu'

### ISSUE THREAD

**Issue by DragosDogioiu** [thygate/stable-diffusion-webui-depthmap-script#200]
Hello, after installing I get the error below. The Depth tab is missing, but the rest of SD works fine. I tried using a fresh sd folder, multiple UI restarts and updated 1111. I am running on colab if it helps.

Restarting UI...
ControlNet v1.1.116
Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 58, in <module>
    from inpaint.mesh import write_mesh, read_mesh, output_3d_photo
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/inpaint/mesh.py", line 12, in <module>
    from vispy import scene, io
  File "/usr/local/lib/python3.10/dist-packages/vispy/scene/__init__.py", line 33, in <module>
    from .visuals import *  # noqa
  File "/usr/local/lib/python3.10/dist-packages/vispy/scene/visuals.py", line 18, in <module>
    from .. import visuals
  File "/usr/local/lib/python3.10/dist-packages/vispy/visuals/__init__.py", line 14, in <module>
    from .axis import AxisVisual  # noqa
  File "/usr/local/lib/python3.10/dist-packages/vispy/visuals/axis.py", line 13, in <module>
    from .text import TextVisual
  File "/usr/local/lib/python3.10/dist-packages/vispy/visuals/text/__init__.py", line 7, in <module>
    from .text import TextVisual  # noqa
  File "/usr/local/lib/python3.10/dist-packages/vispy/visuals/text/text.py", line 18, in <module>
    from ._sdf_cpu import _calc_distance_field
ModuleNotFoundError: No module named 'vispy.visuals.text._sdf_cpu'

**Comment by thygate** [comment]
>ModuleNotFoundError: No module named 'vispy.visuals.text._sdf_cpu'

try reinstalling vispy
