### ISSUE TITLE
Depth map just returning error

### ISSUE THREAD

**Issue by one-agnostik** [thygate/stable-diffusion-webui-depthmap-script#201]
I press generate and it just says error on the right, no explanation. Any idea what I'm doing wrong?

**Comment by thygate** [comment]
post the complete stack trace from the console window

**Comment by one-agnostik** [comment]
Traceback (most recent call last):
  File "C:\Users\audio\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\audio\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\audio\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\audio\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\audio\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\audio\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: "<div class='error'>HTTPError: HTTP Error 429: Too Many Requests</div><div class='performance'><p class='time'>Time taken: <wbr>2.58s</p><p class='vram'>Torch active/reserved: 2067/2082 MiB, <wbr>Sys VRAM: 3929/8192 MiB (47.96%)</p></div>"

**Comment by one-agnostik** [comment]
thanks for replying. Any ideas?

**Comment by thygate** [comment]
that's not the complete stack trace, I cannot make up anything from just that ..
