### ISSUE TITLE
Depthmap ERROR: didn't receive enough output values

### ISSUE THREAD

**Issue by christanrah** [thygate/stable-diffusion-webui-depthmap-script#205]
**Hello all!

I tried to use Dephmap, but it ends with Error ((

Do you know how to fix it?**

DepthMap v0.3.11
device: cuda
Loading model weights from  ./models/leres/res101.pth
Downloading https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download to ./models/leres/res101.pth
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x21C1F037070>, None, '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, False, False, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\ERIK\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\ERIK\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\ERIK\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1171, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "C:\Users\ERIK\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 346, in run_depthmap
    download_file(model_path,"https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download")
  File "C:\Users\ERIK\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1397, in download_file
    torch.hub.download_url_to_file(url, filename)
  File "C:\Users\ERIK\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "C:\Users\ERIK\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ERIK\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\ERIK\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\ERIK\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\ERIK\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\ERIK\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

Traceback (most recent call last):
  File "C:\Users\ERIK\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\ERIK\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\ERIK\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1206, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\ERIK\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1181, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>HTTPError: HTTP Error 429: Too Many Requests</div><div class='performance'><p class='time'>Time taken: <wbr>1.71s</p><p class='vram'>Torch active/reserved: 2069/2082 MiB, <wbr>Sys VRAM: 3792/24576 MiB (15.43%)</p></div>"]

**Comment by thygate** [comment]
seems like the server where it wants to download the models is dropping requests due to high traffic ..

**Comment by cbolich** [comment]
also have this issue

**Comment by cbolich** [comment]
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\autofork\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\autofork\venv\lib\site-packages\gradio\blocks.py", line 1318, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\stable-diffusion-webui\autofork\venv\lib\site-packages\gradio\blocks.py", line 1221, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "F:\stable-diffusion-webui\autofork\venv\lib\site-packages\gradio\blocks.py", line 1196, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>AttributeError: &#x27;str&#x27; object has no attribute &#x27;name&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>3.02s</p><p class='vram'>Torch active/reserved: 2553/2568 MiB, <wbr>Sys VRAM: 4922/24576 MiB (20.03%)</p></div>"]
