### ISSUE TITLE
Error on startup (Event handler (f) did not receive enough output values

### ISSUE THREAD

**Issue by xnuttyxd** [thygate/stable-diffusion-webui-depthmap-script#207]
`Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=1456x816 at 0x1EBFE7F67D0>, None, '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, False, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\Michael\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Michael\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Michael\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1171, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "C:\Users\Michael\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 766, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
UnboundLocalError: local variable 'inpaint_imgs' referenced before assignment

Traceback (most recent call last):
  File "C:\Users\Michael\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Michael\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Michael\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1206, in postprocess_data    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\Michael\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1181, in validate_outputs    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>UnboundLocalError: local variable &#x27;inpaint_imgs&#x27; referenced before assignment</div><div class='performance'><p class='time'>Time taken: <wbr>3.88s</p><p class='vram'>Torch active/reserved: 4398/4508 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"]'

Here is the error i got in my CMD im using these arguments:
Launching Web UI with arguments: --precision full --no-half --opt-split-attention (have tried the half VRAM argument with no change on this error)
This is my first attempt at a depth map and i am a complete novice at AI, SD, blender, coding etc... 

any help would be helpful, thanks :)

**Comment by thygate** [comment]
>UnboundLocalError: local variable 'inpaint_imgs' referenced before assignment

I assume this was a secondary error, something went wrong before that. Please post the entire stack trace from the console.

**Comment by xnuttyxd** [comment]
i had to remake the error but here it is: 

To create a public link, set `share=True` in `launch()`.
Startup time: 21.5s (import torch: 3.0s, import gradio: 2.2s, import ldm: 0.8s, other imports: 2.4s, load scripts: 4.2s, load SD checkpoint: 7.6s, create ui: 1.0s, gradio launch: 0.2s).

DepthMap v0.3.11
device: cuda
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
unexpected EOF, expected 10480012 more bytes. The file might be corrupted.
All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=1456x816 at 0x1FB7FE36F20>, None, '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, False, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\Michael\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Michael\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Michael\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1171, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "C:\Users\Michael\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 766, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
UnboundLocalError: local variable 'inpaint_imgs' referenced before assignment

Traceback (most recent call last):
  File "C:\Users\Michael\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Michael\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Michael\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1206, in postprocess_data    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\Michael\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1181, in validate_outputs    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>UnboundLocalError: local variable &#x27;inpaint_imgs&#x27; referenced before assignment</div><div class='performance'><p class='time'>Time taken: <wbr>3.73s</p><p class='vram'>Torch active/reserved: 4389/4504 MiB, <wbr>Sys VRAM: 6078/6144 MiB (98.93%)</p></div>"]

**Comment by xnuttyxd** [comment]
it worked, thank you sorry for the late replys
