### ISSUE TITLE
amd issues

### ISSUE THREAD

**Issue by ytnurg** [thygate/stable-diffusion-webui-depthmap-script#214]
DepthMap v0.3.11
device: cpu
Loading model weights from  ./models/leres/res101.pth
Downloading https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download to ./models/leres/res101.pth
100%|███████████████████████████████████████████████████████████████████████████████| 506M/506M [00:30<00:00, 17.3MB/s]
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x16C4BFF8550>, None, '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, True, False, False, False, 'u2net', False, 0, 2, False, None, True, True, True, False) {}
Traceback (most recent call last):
  File "C:\Users\Ghost\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Ghost\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Ghost\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1171, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "C:\Users\Ghost\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 766, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
UnboundLocalError: local variable 'inpaint_imgs' referenced before assignment

Traceback (most recent call last):
  File "C:\Users\Ghost\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Ghost\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Ghost\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1206, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\Ghost\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1181, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>UnboundLocalError: local variable &#x27;inpaint_imgs&#x27; referenced before assignment</div><div class='performance'><p class='time'>Time taken: <wbr>33.60s</p></div>"]

**Comment by ytnurg** [comment]
got it to work will post in a bit on how i did it for others!

**Comment by 1arrcy1** [comment]
> Author
> ###

how did you get it working ?

**Comment by ytnurg** [comment]
@echo off

set PYTHON="C:\Users\Ghost\AppData\Local\Programs\Python\Python310\python.exe"
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--precision full --no-half --skip-torch-cuda-test --disable-safe-unpickle
git pull
call webui.bat

**Comment by ytnurg** [comment]
install auto 1111 on computer with the amd put that code in your batch file. run it 2x didnt work the until the second time for me.
