### ISSUE TITLE
Error verifying pickled file

### ISSUE THREAD

**Issue by XTRMsavage** [thygate/stable-diffusion-webui-depthmap-script#218]
`DepthMap v0.3.11
device: cuda
Loading model weights from  ./models/leres/res101.pth
Error verifying pickled file from ./models/leres/res101.pth:
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\modules\safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\modules\safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Error completing request
Arguments: ('task(eoqglb7wx6xgp5i)', 'photo of a (gourmet) cheeseburger, (bacon:1.2), (lettuce), (onion:1.2), (tomato), french fries, beer, cinematic, beautiful', '(bad-hands-5:1.05), easynegative, [( NG_DeepNegative_V1_64T :0.9) :0.1], ng_deepnegative_v1_75t, worst quality, low quality, normal quality, child, (painting, drawing, sketch, cartoon, anime, render, 3d), blurry, deformed, disfigured, morbid, mutated, bad anatomy, bad art, bad teeth, (weird nipples, twisted nipples, deformed nipples, flat nipples), (worst quality, low quality, logo, text, watermark, username), bad_prompt_version2', [], 20, 8, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 6, False, '', 0, False, 'x264', 'mci', 10, 0, 0, False, True, True, True, 'intermediate', 'animation', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <controlnet.py.UiControlNetUnit object at 0x000002402B7834F0>, <controlnet.py.UiControlNetUnit object at 0x000002402B783640>, <controlnet.py.UiControlNetUnit object at 0x000002402B7830D0>, <controlnet.py.UiControlNetUnit object at 0x000002402B783490>, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, False, None, True, False, False, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, 50, 0, 0, 512, 512, False, True, False, False, 0, 1, True, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, False, False, False, False, False, False, 'u2net', False, True, False) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 282, in run
    newmaps, mesh_fi, meshsimple_fi = run_depthmap(processed, p.outpath_samples, inputimages, None,
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master bu\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 352, in run_depthmap
    model.load_state_dict(strip_prefix_if_present(checkpoint['depth_model'], "module."), strict=True)
TypeError: 'NoneType' object is not subscriptable`

The model "res101.pth" is in the models/ leres folder. Why is this happening?

Thanks

**Comment by thygate** [comment]
The download was probably incomplete, delete the model and try again, it
will redownload..
