### ISSUE TITLE
Issue loading Depth Map

### ISSUE THREAD

**Issue by beholdtheiceman** [thygate/stable-diffusion-webui-depthmap-script#235]
Hi all,

I'm very new to this and not super savvy with it. I followed a tutorial on how to install this extension step-for-step and I couldn't get the extension to actually install. When I checked the prompt I saw this message:

Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\Users\Larry\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Larry\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Larry\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 58, in <module>
    from inpaint.mesh import write_mesh, read_mesh, output_3d_photo
  File "C:\Users\Larry\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh.py", line 16, in <module>
    from moviepy.editor import ImageSequenceClip
ModuleNotFoundError: No module named 'moviepy'

Any help would be appreciated.

Thanks!

**Comment by xSemi** [comment]
Have also issue Loading the Depth map butter Abit Different Error.

Error loading script: depthmap.py
Traceback (most recent call last):
  File "N:\Stable\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "N:\Stable\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "N:\Stable\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 50, in <module>
    from lib.multi_depth_model_woauxi import RelDepthModel
ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'
