### ISSUE TITLE
Depth map crashing some time after pressing generate 

### ISSUE THREAD

**Issue by Airburner** [thygate/stable-diffusion-webui-depthmap-script#239]
After some time after pressing Generate button I have error:

Saving faces: 100%|███████████████| 5232425/5232425 [00:17<00:00, 307174.04it/s]
  0%|                                                     | 0/1 [10:34<?, ?it/s]
All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x768 at 0x7F9B024AD5A0>, None, '', '', 0, 2, 512, 512, False, True, False, False, 0, 1, True, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, True, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1184, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "/workspace/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 779, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
  File "/workspace/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 944, in run_3dphoto
    run_3dphoto_videos(mesh_fi, basename, outpath, 300, 40,
  File "/workspace/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 972, in run_3dphoto_videos
    vispy.use(app='egl')
  File "/usr/local/lib/python3.10/dist-packages/vispy/util/wrappers.py", line 93, in use
    use_app(app)
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
  File "/usr/local/lib/python3.10/dist-packages/vispy/app/application.py", line 240, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "EGL":
Could not initialize

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1318, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1221, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1196, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>RuntimeError: Could not import backend &quot;EGL&quot;:
Could not initialize</div><div class='performance'><p class='time'>Time taken: <wbr>11m 59.28s</p><p class='vram'>Torch active/reserved: 12381/12588 MiB, <wbr>Sys VRAM: 13749/16118 MiB (85.3%)</p></div>"]

Generate 3D inpainted mesh. (Sloooow, required for generating videos) is on
dpt_beit_large_384 (midas 3.1)
GPU

on 1 x RTX A4000
8 vCPU 31 GB RAM

**Comment by LanceGao97** [comment]
i have exactly save error with this one, how to fix?

**Comment by semjon00** [comment]
Please run `pip list` in the venv and post the result here.
