### ISSUE TITLE
Mesh is OK ,  Can't render the Movie , I don't know whats wrong.

### ISSUE THREAD

**Issue by LanceGao97** [thygate/stable-diffusion-webui-depthmap-script#242]
Running on a online server , 
Mesh is OK and depth map OK ,  the movie can't render,  why is that,  I searched  a lot issues, didn't finde the anwer

Loading depth model ..
Loading rgb model ..
  0%|                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
Generating inpainted mesh .. (go make some coffee) ..
Generating faces: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [05:40<00:00, 48.65s/it]
Writing mesh file outputs/extras-images/depthmap-0002.ply ...██████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [05:40<00:00, 39.12s/it]
Saving faces: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11295818/11295818 [00:25<00:00, 439414.49it/s]
Writing mesh file outputs/extras-images/depthmap-0002.obj ...███████████████████████████████████████████████████████████████████████████▌| 11252867/11295818 [00:25<00:00, 490342.29it/s]
Saving faces: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11295818/11295818 [00:30<00:00, 368018.12it/s]
  0%|                                                                                                                                                              | 0/1 [07:17<?, ?it/s]
All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=1232x1280 at 0x7F456A5E3A00>, None, '', '', 0, 0, 512, 512, False, True, False, True, 0, 0.752, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, True, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/root/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1184, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "/root/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 779, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
  File "/root/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 944, in run_3dphoto
    run_3dphoto_videos(mesh_fi, basename, outpath, 300, 40,
  File "/root/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 972, in run_3dphoto_videos
    vispy.use(app='egl')
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/util/wrappers.py", line 93, in use
    use_app(app)
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/application.py", line 240, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "EGL":
EGL library not found

Traceback (most recent call last):
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1206, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1181, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>RuntimeError: Could not import backend &quot;EGL&quot;:
EGL library not found</div><div class='performance'><p class='time'>Time taken: <wbr>7m 39.95s</p><p class='vram'>Torch active/reserved: 20104/20154 MiB, <wbr>Sys VRAM: 20410/24257 MiB (84.14%)</p></div>"]

**Comment by AlexeyPogorelov** [comment]
The same on my Windows and Ubuntu environments (GPU and CPU)

**Comment by gigius** [comment]
The same error on google collab
