### ISSUE TITLE
name 'video_mesh_data' is not defined

### ISSUE THREAD

**Issue by szriru** [thygate/stable-diffusion-webui-depthmap-script#247]
```
Arguments: ('outputs/extras-images\\depthmap-0003.obj', '300', '30', 1, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', False, 0, 2) {}
Traceback (most recent call last):
  File "C:\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1090, in run_makevideo
    fn_saved = run_3dphoto_videos(fn_mesh, basename, outpath, num_frames, num_fps, crop_border, vid_traj, x_shift_range, y_shift_range, z_shift_range, [''], dolly, fnExt, vid_ssaa)
  File "C:\automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 977, in run_3dphoto_videos
    del video_mesh_data
NameError: name 'video_mesh_data' is not defined
```

I got this error. And deleting this line solved the problem.
https://github.com/thygate/stable-diffusion-webui-depthmap-script/blob/e394d38ccaf16264a199be5ce668b140dbf7b1c1/scripts/depthmap.py#L977

I don't know why this line exists while declaration of the variable is just above.
Should I PR?

**Comment by gwntd541** [comment]
I have encountered the same issue, is there a fix for this? Was this cause by improper setup?

**Comment by szriru** [comment]
> ###
> **[gwntd541](/gwntd541) ** commented [Sep 25, 2023](#issuecomment-1733059377) •

I don't remember but I think I just deleted the line I mentioned.
