### ISSUE TITLE
Multiple Exceptions: zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Dusty12345** [thygate/stable-diffusion-webui-depthmap-script#25]
Hi Team,
 
I used to be able to run DepthMap using v.0.7 but it stopped working. I reinstalled following the instructions and receive errors in the logs that prevent the depth maps from being generated. 
Any help is appreciated, please let me know if I installed incorrectly but the instructions are very straightforward.

**DepthMap Log:**

```DepthMap v0.1.8
device: cuda
Loading midas model weights ..
./models/midas/dpt_hybrid-midas-501f0c75.pt
Error verifying pickled file from ./models/midas/dpt_hybrid-midas-501f0c75.pt:
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\safe.py", line 83, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Users\dusty\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\dusty\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "C:\stable-diffusion-webui\modules\safe.py", line 98, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error completing request
Arguments: ('hero sitting on the top of a rooftop overlooking gotham city, 8k, ultra details, HD', 'text, letters, words, signature, script, boring, dull, watermark, low quality, worst quality, jpeg artifacts', 'None', 'None', 45, 0, True, False, 6, 1, 7, -1.0, -1.0, 0, 0, 0, False, 576, 960, True, 0.75, 0, 0, 1, '<div class="dynamic-prompting">\n    <h3><strong>Combinations</strong></h3>\n\n    Choose a number of terms from a list, in this case we choose two artists: \n    <code class="codeblock">{2$$artist1|artist2|artist3}</code><br/>\n\n    If $$ is not provided, then 1$$ is assumed.<br/><br/>\n\n    If the chosen number of terms is greater than the available terms, then some terms will be duplicated, otherwise chosen terms will be unique. This is useful in the case of wildcards, e.g.\n    <code class="codeblock">{2$$__artist__}</code> is equivalent to <code class="codeblock">{2$$__artist__|__artist__}</code><br/><br/>\n\n    A range can be provided:\n    <code class="codeblock">{1-3$$artist1|artist2|artist3}</code><br/>\n    In this case, a random number of artists between 1 and 3 is chosen.<br/><br/>\n\n    Wildcards can be used and the joiner can also be specified:\n    <code class="codeblock">{{1-$$and$$__adjective__}}</code><br/>\n\n    Here, a random number between 1 and 3 words from adjective.txt will be chosen and joined together with the word \'and\' instead of the default comma.\n\n    <br/><br/>\n\n    <h3><strong>Wildcards</strong></h3>\n    \n\n    <br/>\n    If the groups wont drop down click <strong onclick="check_collapsibles()" style="cursor: pointer">here</strong> to fix the issue.\n\n    <br/><br/>\n\n    <code class="codeblock">WILDCARD_DIR: C:\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts\\wildcards</code><br/>\n    <small onload="check_collapsibles()">You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in C:\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts\\wildcards. <code class="codeblock">__&#60;folder&#62;/mywildcards__</code> will then become available.</small>\n</div>\n\n', True, False, 1, False, False, 100, 0.7, False, False, False, False, False, False, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, 0, 1, 384, 384, True, True, True, True, False, 1, False, False, False, '', 1, '', 0, '', True, False, False, 1.0, 2.0, 'a painting in', 'style', 'picture frame, portrait photo', None) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\scripts\depthmap.py", line 103, in run
    model = DPTDepthModel(
  File "C:\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 105, in __init__
    self.load(path)
  File "C:\stable-diffusion-webui\repositories\midas\midas\base_model.py", line 13, in load
    if "optimizer" in parameters:
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\ui.py", line 188, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\stable-diffusion-webui\modules\scripts.py", line 290, in run
    processed = script.run(p, *script_args)
  File "C:\stable-diffusion-webui\scripts\depthmap.py", line 253, in run
    del model
UnboundLocalError: local variable 'model' referenced before assignment```

**Comment by thygate** [comment]
>Error verifying pickled file from ./models/midas/dpt_hybrid-midas-501f0c75.pt:

sounds like the midas model weights file `dpt_hybrid` is corrupted ?

Delete that file and try again, it will re-download it on next attempt.

**Comment by Dusty12345** [comment]
Appreciate the quick response! Will try that and report back

**Comment by thygate** [comment]
it's downloaded directly from the official repository, so it likely got corrupted during download.

**Comment by thygate** [comment]
accidentally closed the issue there, still waiting for your feedback. Re-downloading the weights should solve your issue.

**Comment by Dusty12345** [comment]
All good it did resolve the issue, thank you for your your help!!

**Comment by thygate** [comment]
Have fun! =)
