### ISSUE TITLE
Depth Map : FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Lexovy** [thygate/stable-diffusion-webui-depthmap-script#251]
Hi Everyone ! 

Not very comfortable with code & processes to be honnest and a really noob for computers but I wanted to try the Depth Map on SD but I keep getting this error when trying to generate on the Depth Tab. 
I'm getting this error on the console, can someone help ? Thanks a lot.

DepthMap v0.3.11 (baf6946e)
device: cuda
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

wholeImage being processed in : 896
Adjust factor is: 1.8413299663299663
Selecting patches ...
Target resolution:  (1849, 3300, 3)
Resulting depthmap resolution will be : (816, 1456)
patches to process: 12
         processing patch 0 / 11 | [156   8 677 677]
         processing patch 1 / 11 | [304   8 677 677]
         processing patch 2 / 11 | [452   8 677 677]
         processing patch 3 / 11 | [601   8 677 677]
         processing patch 4 / 11 | [181 181 626 626]
         processing patch 5 / 11 | [330 181 626 626]
         processing patch 6 / 11 | [478 181 626 626]
         processing patch 7 / 11 | [626 181 626 626]
         processing patch 8 / 11 | [297   0 395 395]
         processing patch 9 / 11 | [445   0 395 395]
         processing patch 10 / 11 | [593   0 395 395]
         processing patch 11 / 11 | [741   0 395 395]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:13<00:00, 13.89s/it]
Done.
All done.
Traceback (most recent call last):
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "D:\stable-diffusion\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\aeski\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\aeski\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\aeski\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aeski\\AppData\\Local\\Temp\\gradio\\tmp5i44zug2.png'

**Comment by Lexovy** [comment]
Alright for some reasons after installing ControlNet, it solved the problem. Don't really understand why but it works now & have no more error problems.
Something I didn't notice though is that it was saving the generated depth maps in the output files even though it was giving me an error.
