### ISSUE TITLE
UnboundLocalError: local variable 'inpaint_imgs' referenced before assignment

### ISSUE THREAD

**Issue by alex2lee** [thygate/stable-diffusion-webui-depthmap-script#261]
Hi there, I'm getting the following error when attempting to generate with the options "Generate 3D inpainted mesh. (Sloooow, required for generating videos)" and "Generate 4 demo videos with 3D inpainted mesh."

Any idea what might be happening? Thanks so much.

```
DepthMap v0.3.11 (0cc0ee1b)
device: cpu
Loading model weights from  ./models/leres/res101.pth
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=720x720 at 0x2C48E6E30>, None, '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, True, False, False, False, False, 'u2net', False, 0, 2, False, None, True, True, True, False) {}
Traceback (most recent call last):
  File "/Users/devinfinzer/code/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/devinfinzer/code/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/devinfinzer/code/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1184, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "/Users/devinfinzer/code/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 779, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
UnboundLocalError: local variable 'inpaint_imgs' referenced before assignment
```

**Comment by semjon00** [comment]
Probably solved in the latest version
