### ISSUE TITLE
"depth" always crashes when I hit generate. Alienware 17r4 3080

### ISSUE THREAD

**Issue by MercedesBends** [thygate/stable-diffusion-webui-depthmap-script#265]
Tried different size of input images (including the examples at the bottom of the page) nothing seems to work. Always just get an "Error" message. Tried CPU and GPU. Tried different models. I'm out of ideas. Other features of the install work. Any help welcome. Thank you.

**Comment by semjon00** [comment]
Please provide the full console output.

**Comment by semjon00** [comment]
When you start the WebUI, it should show you the link you should enter/click to get to the interface (with tabs, etc.). This link is a part of console output. Please try to hit generate, get an error, and then copy-paste everything from the console output here.

**Comment by semjon00** [comment]
When you start the WebUI, a black box with text appears. I think you will see it once you click here.
![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/54073010/f84a8415-d338-4fd4-b0c4-410ae9c459db)
This text describes some of the inner events happening with the WebUI and the plugin - and is sometimes very insightful.

**Comment by MercedesBends** [comment]
Aha - apologies. I completely forgot the CMD window was part of it. D'Oh! 

Already up to date.
venv "C:\Users\auser\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements
Installing imageio-ffmpeg requirement for depthmap script
Installing pyqt5 requirement for depthmap script

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [cc6cb27103] from C:\Users\auser\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.6s (import torch: 4.0s, import gradio: 2.0s, import ldm: 0.9s, other imports: 1.9s, setup codeformer: 0.1s, load scripts: 4.8s, create ui: 0.6s, gradio launch: 0.2s).
preload_extensions_git_metadata for 9 extensions took 0.64s
Creating model from config: C:\Users\auser\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: Doggettx... done.
Textual inversion embeddings loaded(0):
Model loaded in 8.7s (load weights from disk: 3.9s, create model: 0.5s, apply weights to model: 0.7s, apply half(): 0.8s, move model to device: 2.3s, calculate empty prompt: 0.4s).

DepthMap v0.3.12 (394ffa7b)
device: cuda
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

wholeImage being processed in : 672
Adjust factor is: 1.5503875968992247
Selecting patches ...
Target resolution:  (2084, 2067, 3)
Resulting depthmap resolution will be : (381, 378)
patches to process: 7
         processing patch 0 / 6 | [ 39  39 334 334]
         processing patch 1 / 6 | [ 31 154 227 227]
         processing patch 2 / 6 | [ 92 154 227 227]
         processing patch 3 / 6 | [158  97 218 218]
         processing patch 4 / 6 | [158 158 218 218]
         processing patch 5 / 6 | [  0 184 164 164]
         processing patch 6 / 6 | [184  61 164 164]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:13<00:00, 13.36s/it]
Done.
All done.
Traceback (most recent call last):
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\Users\auser\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\auser\\AppData\\Local\\Temp\\gradio\\tmpvnk2gvla.png'

DepthMap v0.3.12 (394ffa7b)
device: cuda
Loading model weights from  ./models/midas/midas_v21-f6b98070.pt
Downloading https://github.com/AlexeyAB/MiDaS/releases/download/midas_dpt/midas_v21-f6b98070.pt to ./models/midas/midas_v21-f6b98070.pt
100%|███████████████████████████████████████████████████████████████████████████████| 403M/403M [00:11<00:00, 35.9MB/s]
Loading weights:  ./models/midas/midas_v21-f6b98070.pt
Downloading: "https://github.com/facebookresearch/WSL-Images/zipball/main" to C:\Users\auser/.cache\torch\hub\main.zip
Downloading: "https://download.pytorch.org/models/ig_resnext101_32x8-c38310e5.pth" to C:\Users\auser/.cache\torch\hub\checkpoints\ig_resnext101_32x8-c38310e5.pth
100%|███████████████████████████████████████████████████████████████████████████████| 340M/340M [00:04<00:00, 73.3MB/s]
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

wholeImage being processed in : 576
Adjust factor is: 1.680672268907563
Selecting patches ...
Target resolution:  (1936, 1921, 3)
Resulting depthmap resolution will be : (381, 378)
patches to process: 12
         processing patch 0 / 11 | [  0 114 266 266]
         processing patch 1 / 11 | [ 57 114 266 266]
         processing patch 2 / 11 | [119  62 255 255]
         processing patch 3 / 11 | [119 119 255 255]
         processing patch 4 / 11 | [  0 170 151 151]
         processing patch 5 / 11 | [  0 227 151 151]
         processing patch 6 / 11 | [ 57 227 151 151]
         processing patch 7 / 11 | [113 227 151 151]
         processing patch 8 / 11 | [170 227 151 151]
         processing patch 9 / 11 | [227 113 151 151]
         processing patch 10 / 11 | [227 170 151 151]
         processing patch 11 / 11 | [227 227 151 151]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:09<00:00,  9.89s/it]
Done.
All done.
Traceback (most recent call last):
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\Users\auser\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\auser\\AppData\\Local\\Temp\\gradio\\tmpwexlaxjg.png'

DepthMap v0.3.12 (394ffa7b)
device: cuda
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

wholeImage being processed in : 672
Adjust factor is: 1.5503875968992247
Selecting patches ...
Target resolution:  (2084, 2067, 3)
Resulting depthmap resolution will be : (381, 378)
patches to process: 7
         processing patch 0 / 6 | [ 39  39 334 334]
         processing patch 1 / 6 | [ 31 154 227 227]
         processing patch 2 / 6 | [ 92 154 227 227]
         processing patch 3 / 6 | [158  97 218 218]
         processing patch 4 / 6 | [158 158 218 218]
         processing patch 5 / 6 | [  0 184 164 164]
         processing patch 6 / 6 | [184  61 164 164]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.30s/it]
Done.
All done.
Traceback (most recent call last):
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\Users\auser\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\auser\\AppData\\Local\\Temp\\gradio\\tmprvvma70h.png'

DepthMap v0.3.12 (394ffa7b)
device: cuda
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

wholeImage being processed in : 672
Adjust factor is: 1.5503875968992247
Selecting patches ...
Target resolution:  (2084, 2067, 3)
Resulting depthmap resolution will be : (381, 378)
patches to process: 7
         processing patch 0 / 6 | [ 39  39 334 334]
         processing patch 1 / 6 | [ 31 154 227 227]
         processing patch 2 / 6 | [ 92 154 227 227]
         processing patch 3 / 6 | [158  97 218 218]
         processing patch 4 / 6 | [158 158 218 218]
         processing patch 5 / 6 | [  0 184 164 164]
         processing patch 6 / 6 | [184  61 164 164]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.60s/it]
Done.
All done.
Traceback (most recent call last):
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\Users\auser\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\auser\\AppData\\Local\\Temp\\gradio\\tmp9d2mufnj.png'

**Comment by MercedesBends** [comment]
Apologies - I forgot the cmd window was part of SD. I've booted it and done one depth attempt in SD - which crashed. 

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), 873 bytes | 67.00 KiB/s, done.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * [new branch]        callback-after_extra_networks_activate -> origin/callback-after_extra_networks_activate
Already up to date.
venv "C:\Users\auser\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements
Installing imageio-ffmpeg requirement for depthmap script
Installing pyqt5 requirement for depthmap script

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [cc6cb27103] from C:\Users\auser\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.6s (import torch: 4.5s, import gradio: 2.7s, import ldm: 1.0s, other imports: 2.4s, setup codeformer: 0.1s, load scripts: 5.0s, create ui: 0.6s, gradio launch: 0.2s).
preload_extensions_git_metadata for 9 extensions took 0.58s
Creating model from config: C:\Users\auser\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: Doggettx... done.
Textual inversion embeddings loaded(0):
Model loaded in 7.0s (load weights from disk: 4.0s, create model: 0.5s, apply weights to model: 0.7s, apply half(): 0.7s, move model to device: 1.0s).

DepthMap v0.3.12 (394ffa7b)
device: cuda
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

wholeImage being processed in : 672
Adjust factor is: 1.5503875968992247
Selecting patches ...
Target resolution:  (2084, 2067, 3)
Resulting depthmap resolution will be : (381, 378)
patches to process: 7
         processing patch 0 / 6 | [ 39  39 334 334]
         processing patch 1 / 6 | [ 31 154 227 227]
         processing patch 2 / 6 | [ 92 154 227 227]
         processing patch 3 / 6 | [158  97 218 218]
         processing patch 4 / 6 | [158 158 218 218]
         processing patch 5 / 6 | [  0 184 164 164]
         processing patch 6 / 6 | [184  61 164 164]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:13<00:00, 13.56s/it]
Done.
All done.
Traceback (most recent call last):
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\auser\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\Users\auser\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\auser\\AppData\\Local\\Temp\\gradio\\tmpax1ife8o.png'

**Comment by semjon00** [comment]
😢

**Comment by MercedesBends** [comment]
Haha. That emoji made me laugh. Thank you for the help.

**Comment by semjon00** [comment]
@MercedesBends I think this is not specific to the plugin. Please see this: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11040
The main suggestion is to manually create this folder: 'C:\Users\auser\AppData\Local\Temp\gradio\'.

**Comment by MercedesBends** [comment]
Thank you! Much appreciated I'll give that a go.
