### ISSUE TITLE
Errors When Generating anything

### ISSUE THREAD

**Issue by XSGrimm** [thygate/stable-diffusion-webui-depthmap-script#273]
Im having errors Generating anything 
i get this errors everytime Tried CPU GPU but nothing

Generating inpainted mesh .. (go make some coffee) ..
Generating faces: 100%|██████████████████████████████████████████████████████████████████| 7/7 [05:04<00:00, 43.44s/it]
Writing mesh file outputs/extras-images\depthmap-0005.obj ...████████████████████████████| 7/7 [05:04<00:00, 33.61s/it]
Saving faces: 100%|████████████████████████████████████████████████████| 10600287/10600287 [00:38<00:00, 276966.68it/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [06:07<00:00, 367.48s/it]
All done.
Traceback (most recent call last):
  File "D:\AI\Gen\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\Gen\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\AI\Gen\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\AI\Gen\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "D:\AI\Gen\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Program Files\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Program Files\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Program Files\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XSGrimm\\AppData\\Local\\Temp\\gradio\\tmpyb4lg0kq.png'

**Comment by thygate** [comment]
>Writing mesh file outputs/extras-images\depthmap-0005.obj

The mesh seems to have been saved though ..

**Comment by XSGrimm** [comment]
where??

**Comment by thygate** [comment]
The path in the quote, /output/extras-images/, isn't the file depthmap-0005.obj in that folder ?

**Comment by semjon00** [comment]
@XSGrimm https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/265#issuecomment-1613850617
But your path should be 'C:\Users\XSGrimm\AppData\Local\Temp\gradio\'

**Comment by Harri1118** [comment]
I have this issue as well!
