### ISSUE TITLE
Depth generated, but other weird error

### ISSUE THREAD

**Issue by enzyme69** [thygate/stable-diffusion-webui-depthmap-script#276]
On Mac, I got the depth output, but not getting the stereoscopic side by side images, with error below:

```
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1225, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 735, in run_depthmap
    stereoimages = create_stereoimages(inputimages[count], img_output, stereo_divergence, stereo_separation, stereomodes, stereo_balance, stereo_fill)
TypeError: create_stereoimages() takes from 3 to 6 positional arguments but 7 were given

Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: "<div class='error'>TypeError: create_stereoimages() takes from 3 to 6 positional arguments but 7 were given</div><div class='performance'><p class='time'>Time taken: <wbr>9m 15.01s</p></div>"
```

**Comment by semjon00** [comment]
Please update the extension one more time. You can update the extension in the Extensions tab. If this does not help, please delete the stable-diffusion-webui-depthmap-script folder (can be found in the extensions folder) and install the script again. Please let us know if this helped.

**Comment by semjon00** [comment]
@enzyme69 If you still have this issue, please upgrade the extension, and if it persists, please let us know.
