### ISSUE TITLE
When using the hybrid model : RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by Extraltodeus** [thygate/stable-diffusion-webui-depthmap-script#28]
I thought I made a mistake in my scripts but then I tried with yours and had the same problem. Now I don't see any difference in between your code and the one in midas repository about loading the hybrid model so I'm kind of clueless about why it does not work (I have not tried directly with the midas repo).
```

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/img2img.py", line 137, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/content/stable-diffusion-webui/modules/scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "/content/stable-diffusion-webui/scripts/depthmap.py", line 188, in run
    prediction = model.forward(sample)
  File "/content/stable-diffusion-webui/repositories/midas/midas/dpt_depth.py", line 108, in forward
    return super().forward(x).squeeze(dim=1)
  File "/content/stable-diffusion-webui/repositories/midas/midas/dpt_depth.py", line 71, in forward
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)
  File "/content/stable-diffusion-webui/repositories/midas/midas/vit.py", line 59, in forward_vit
    glob = pretrained.model.forward_flex(x)
  File "/content/stable-diffusion-webui/repositories/midas/midas/vit.py", line 127, in forward_flex
    x = self.patch_embed.backbone(x)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/timm/models/resnetv2.py", line 409, in forward
    x = self.forward_features(x)
  File "/usr/local/lib/python3.8/site-packages/timm/models/resnetv2.py", line 403, in forward_features
    x = self.stem(x)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/timm/models/layers/std_conv.py", line 70, in forward
    self.weight.view(1, self.out_channels, -1), None, None,
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


```

Would you happen to be less in the darkness than me?

**Comment by thygate** [comment]
did you try deleting the dpt_hybrid model, and re-downloading ?

**Comment by Extraltodeus** [comment]
> I'm not sure what's going on here ... What exactly are you testing with .. ?

With your script as well as mines. img2img and any image gives me same issue.

> did you try deleting the dpt_hybrid model, and re-downloading ?

Gotta try

**Comment by thygate** [comment]
Just verified that everything is still working, and it is as far as i can tell ... img2img with dpt_hybrid ...

if other models are working i suspect the used midas model (hybrid) is corrupted ?

**Comment by Extraltodeus** [comment]
This is strange. I deleted/redownloaded the model but get the same issue. I wonder if that's not a python version issue or something similar. I guess I'll cut the hybrid out for now.

**Comment by thygate** [comment]
strange indeed ... I don't have an answer at this time ..

Dumb suggestion, but have you tried rebooting perhaps ? I've had the problem of running out of VRAM after running the midas network a large number of times, so i suspect there is still some problem in there somewhere ..

**Comment by Extraltodeus** [comment]
I'm running on colab and it says that I still have enough ram to feed 3 young chromium browsers.
