### ISSUE TITLE
RuntimeError: Download failed

### ISSUE THREAD

**Issue by vigfuz** [thygate/stable-diffusion-webui-depthmap-script#283]
Keep getting this error when the generator starts to try and output the 3D generated mesh. I have also done as it suggests and downloaded the files and put them in the `/models/3dphoto` folder but it does not matter and I get the same error message.

```
Running 3D Photo Inpainting ..
Downloading https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth to ./models/3dphoto/edge_model.pth
All done.
*** Error completing request
*** Arguments: (0, <PIL.Image.Image image mode=RGB size=1456x816 at 0x15805F820>, None, '', '', 1, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 0, 'polylines_sharp', 0, True, True, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
    Traceback (most recent call last):
      File "/Users/vigfus/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 888, in run_3dphoto
        ensure_file_downloaded(edgemodel_path,"https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth")
      File "/Users/vigfus/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1476, in ensure_file_downloaded
        raise RuntimeError('Download failed. Try again later or manually download the file to that location.')
    RuntimeError: Download failed. Try again later or manually download the file to that location.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/vigfus/stable-diffusion-webui/modules/call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "/Users/vigfus/stable-diffusion-webui/modules/call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "/Users/vigfus/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1236, in run_generate
        outputs, mesh_fi, meshsimple_fi = run_depthmap(
      File "/Users/vigfus/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 835, in run_depthmap
        mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa, inpaint_vids)
      File "/Users/vigfus/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1006, in run_3dphoto
        del rgb_model
    UnboundLocalError: local variable 'rgb_model' referenced before assignment

---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>UnboundLocalError: local variable &#x27;rgb_model&#x27; referenced before assignment</div><div class='performance'><p class='time'>Time taken: <wbr>2m 26.24s</p></div>"]
```

Any suggestions on why this is happening and how to fix this?

### My setup:

Macbook pro

- 2,4GHz Quad-Core Intel Core i5
- Intel iris plus graphics 655 1536 mb
- 16GB ram 2133MHz
- Mac OS Ventura 13.4.1

Stabel diffusion

- version: v1.4.1
- Python: 3.10.7
- Torch: 2.0.1
- Xformers: N/A
- Gradio: 3.32.0

**Comment by thygate** [comment]
please make sure the manually downloaded files have underscores in their names, and not a hyphen.
eg : "./models/3dphoto/edge_model.pth"

**Comment by vigfuz** [comment]
🤦‍♂️ Thanks @thygate , that was almost too embarrassing 😅

**Comment by thygate** [comment]
It's my mistake, I spent quite a bit staring at it myself the first time this popped up .. :blush:

glad you have it solved.
