### ISSUE TITLE
Could not import backend "EGL": EGL library not found

### ISSUE THREAD

**Issue by calvinsunx** [thygate/stable-diffusion-webui-depthmap-script#288]
can you help me!!
i can't produce video

**Comment by calvinsunx** [comment]
Could not import backend "EGL": EGL library not found

**Comment by semjon00** [comment]
@calvinsunx Please provide details about your system. Do you use Windows, Linux or MacOS? Please provide the full console output.

**Comment by NewTurn2017** [comment]
ubuntu : RuntimeError: Could not import backend "EGL": Could not initialize

**Comment by semjon00** [comment]
Please provide the output from the terminal.

**Comment by semjon00** [comment]
Please type this into the terminal: `sudo apt-get install libgles2-mesa-dev libegl1-mesa-dev`. Does this solve the issue?

**Comment by NewTurn2017** [comment]
*** Error completing request
*** Arguments:
('/home/ubuntu/storage/stable-diffusion-webui/outputs/extras-images/depthmap-0000.obj',
'300', '30', 1, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', False,
'mp4', '3') {}
    Traceback (most recent call last):
      File
"/home/ubuntu/storage/stable-diffusion-webui/modules/call_queue.py", line
55, in f
        res = list(func(*args, **kwargs))
      File
"/home/ubuntu/storage/stable-diffusion-webui/modules/call_queue.py", line
35, in f
        res = func(*args, **kwargs)
      File
"/home/ubuntu/storage/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/src/core.py",
line 620, in run_makevideo
        fn_saved = run_3dphoto_videos(fn_mesh, basename, outpath,
num_frames, num_fps, crop_border, vid_traj, x_shift_range,
      File
"/home/ubuntu/storage/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/src/core.py",
line 496, in run_3dphoto_videos
        vispy.use(app='egl')
      File
"/home/ubuntu/storage/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/util/wrappers.py",
line 93, in use
        use_app(app)
      File
"/home/ubuntu/storage/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/_default_app.py",
line 47, in use_app
        default_app = Application(backend_name)
      File
"/home/ubuntu/storage/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/application.py",
line 47, in __init__
        self._use(backend_name)
      File
"/home/ubuntu/storage/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/application.py",
line 240, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "EGL":
    Could not initialize

2023년 7월 20일 (목) 오후 7:23, Semjon Kravtšenko ***@***.***>님이 작성:

**Comment by semjon00** [comment]
Thank you. Does this also occur after you installed the needed packages? `sudo apt-get install libgles2-mesa-dev libegl1-mesa-dev`

**Comment by semjon00** [comment]
@thygate I guess we need to add more `vispy.use` fallbacks in case initializing EGL fails.

With the feeling of a job well-done 😀, I will take a break - how long I don't know yet - anywhere from 3 days to 2 weeks. Could you implement this please?

**Comment by greatwolf** [comment]
I'm running into the same exact issue when running this on kaggle using this notebook https://www.kaggle.com/code/qq2575044704/stable-diffusion-webui

**Comment by old90** [comment]
> Thank you. Does this also occur after you installed the needed packages? `sudo apt-get install libgles2-mesa-dev libegl1-mesa-dev`
ubuntu 
This error is still reported after installation.

**Comment by old90** [comment]
> Thank you. Does this also occur after you installed the needed packages? `sudo apt-get install libgles2-mesa-dev libegl1-mesa-dev`

ubuntu 
This error is still reported after installation. 😞

**Comment by MohamedAliRashad** [comment]
Any solutions for this ?

**Comment by andysingal** [comment]
> apt-get install libgles2-mesa-dev libegl1-mesa-dev

is this resolved?

**Comment by 994020919** [comment]
*** Arguments: ('/root/autodl-tmp/webui_outputs/extras-images/depthmap-0004.obj', '120', '24', 1, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', False, 'mp4', '3') {}
    Traceback (most recent call last):
      File "/root/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/root/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/root/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/src/core.py", line 634, in run_makevideo
        fn_saved = run_3dphoto_videos(fn_mesh, basename, outpath, num_frames, num_fps, crop_border, vid_traj, x_shift_range,
      File "/root/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/src/core.py", line 510, in run_3dphoto_videos
        vispy.use(app='egl')
      File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/util/wrappers.py", line 93, in use
        use_app(app)
      File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/_default_app.py", line 47, in use_app
        default_app = Application(backend_name)
      File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/application.py", line 47, in __init__
        self._use(backend_name)
      File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/vispy/app/application.py", line 240, in _use
        raise RuntimeError(msg)
    RuntimeError: Could not import backend "EGL":
    EGL library not found



I'm having a similar problem, has anyone solved it yet? How was it solved?

**Comment by jaggzh** [comment]
I get the error even with the debs installed (I'm in docker):
```
Loading mesh ..
*** Error completing request
*** Arguments: ('/output/extras/depthmap-0002.obj', '300', '40', 1, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', False, 'mp4', '3') {}
Traceback (most recent call last):
File "/stable-diffusion-webui/modules/call_queue.py", line 57, in f
res = list(func(*args, **kwargs))
File "/stable-diffusion-webui/modules/call_queue.py", line 36, in f
res = func(*args, **kwargs)
File "/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/src/core.py", line 634, in run_makevideo
fn_saved = run_3dphoto_videos(fn_mesh, basename, outpath, num_frames, num_fps, crop_border, vid_traj, x_shift_range,
File "/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/src/core.py", line 510, in run_3dphoto_videos
vispy.use(app='egl')
File "/usr/local/lib/python3.10/site-packages/vispy/util/wrappers.py", line 93, in use
use_app(app)
File "/usr/local/lib/python3.10/site-packages/vispy/app/_default_app.py", line 47, in use_app
default_app = Application(backend_name)
File "/usr/local/lib/python3.10/site-packages/vispy/app/application.py", line 47, in __init__
self._use(backend_name)
File "/usr/local/lib/python3.10/site-packages/vispy/app/application.py", line 240, in _use
raise RuntimeError(msg)
RuntimeError: Could not import backend "EGL":
Could not initialize
```

**Comment by jaggzh** [comment]
Okay, I modified the thing to default to pyqt6 if it detects linux.  Now the EGL error doesn't show in the ui (it's just sitting there counting up the time though), and the console's showing other errors.  I've not resolved it yet.
```
WARNING: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
2023-10-23 05:59:06 WARNING [vispy] From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
2023-10-23 05:59:06 WARNING [vispy] Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, offscreen, vkkhrdisplay, wayland, vnc, xcb, minimal, linuxfb, wayland-egl, minimalegl.

2023-10-23 05:59:06 WARNING [vispy] This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, offscreen, vkkhrdisplay, wayland, vnc, xcb, minimal, linuxfb, wayland-egl, minimalegl.
```

**Comment by 994020919** [comment]
> ubuntu

I'm on ubuntu as well, did you finally fix it?

**Comment by ItsCrea** [comment]
Same problen on Runpod. **EGL library not found**
Is there any solution?
