### ISSUE TITLE
Missing output value

### ISSUE THREAD

**Issue by MartonKT** [thygate/stable-diffusion-webui-depthmap-script#307]
Hey guys,

I'm at the very beginning of my SD journey, just started to play around, focusing mainly on the Depth Map videos. 
My issue is that I just can't figure out what's the missing output value. What do you recommend?

Traceback (most recent call last):
  File "D:\Net programok\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Net programok\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Net programok\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\Net programok\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html]
Received outputs:
    [None, "", "<div class='error'>AttributeError: &#x27;str&#x27; object has no attribute &#x27;df&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>0.00s</p></div>"]

**Comment by graemeniedermayer** [comment]
Quick fix would be removing the last ".df" on line 56 of core.py

You could also revert to and older commit as discussed here https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/308

**Comment by semjon00** [comment]
Sorry, my bad. Fixed now.
