### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by T3chRomanc3r** [thygate/stable-diffusion-webui-depthmap-script#31]
```
Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\voldy\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\voldy\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "C:\voldy\stable-diffusion-webui\scripts\depthmap.py", line 72
    <title>stable-diffusion-webui-depthmap-script/depthmap.py at main · thygate/stable-diffusion-webui-depthmap-script</title>
                                                                      ^
SyntaxError: invalid character '·' (U+00B7)

```

**Comment by thygate** [comment]
><title>stable-diffusion-webui-depthmap-script/depthmap.py at main

Looks like you downloaded the `depthmap.py` script as html.

Please re-download the script using this url :
https://raw.githubusercontent.com/thygate/stable-diffusion-webui-depthmap-script/main/depthmap.py

**Comment by T3chRomanc3r** [comment]
Installed script from extensions panel, everything is working now. Thank you
