### ISSUE TITLE
AttributeError: 'Block' object has no attribute 'drop_path'

### ISSUE THREAD

**Issue by AugmentedRealityCat** [thygate/stable-diffusion-webui-depthmap-script#323]
Just reporting the following as instructed in the GUI. 
Was trying to generate a depthmap from a large picture, as a large depth map (2048x3072) using ZoeDepth NK

```
Please report this issue [here](https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues). Make sure to provide the full stacktrace:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\common_ui.py", line 526, in run_generate
    input_i, type, result = next(gen_obj)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 326, in core_generation_funnel
    raise e
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 182, in core_generation_funnel
    model_holder.get_raw_prediction(inputimages[count], net_width, net_height)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\depthmap_generation.py", line 290, in get_raw_prediction
    raw_prediction = estimatezoedepth(input, self.depth_model, net_width, net_height)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\depthmap_generation.py", line 346, in estimatezoedepth
    prediction = model.infer_pil(img)
  File "C:\stable-diffusion-webui\venvopt\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\dzoedepth\models\depth_model.py", line 141, in infer_pil
    out_tensor = self.infer(x, pad_input=pad_input, with_flip_aug=with_flip_aug, **kwargs)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\dzoedepth\models\depth_model.py", line 126, in infer
    return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\dzoedepth\models\depth_model.py", line 110, in infer_with_flip_aug
    out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\dzoedepth\models\depth_model.py", line 88, in _infer_with_pad_aug
    out = self._infer(x)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\dzoedepth\models\depth_model.py", line 55, in _infer
    return self(x)['metric_depth']
  File "C:\stable-diffusion-webui\venvopt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\dzoedepth\models\zoedepth_nk\zoedepth_nk_v1.py", line 178, in forward
    rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
  File "C:\stable-diffusion-webui\venvopt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\dzoedepth\models\base_models\midas.py", line 268, in forward
    rel_depth = self.core(x)
  File "C:\stable-diffusion-webui\venvopt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User/.cache\torch\hub\intel-isl_MiDaS_master\midas\dpt_depth.py", line 166, in forward
    return super().forward(x).squeeze(dim=1)
  File "C:\Users\User/.cache\torch\hub\intel-isl_MiDaS_master\midas\dpt_depth.py", line 114, in forward
    layers = self.forward_transformer(self.pretrained, x)
  File "C:\Users\User/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\beit.py", line 15, in forward_beit
    return forward_adapted_unflatten(pretrained, x, "forward_features")
  File "C:\Users\User/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\utils.py", line 86, in forward_adapted_unflatten
    exec(f"glob = pretrained.model.{function_name}(x)")
  File "", line 1, in 
  File "C:\Users\User/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\beit.py", line 125, in beit_forward_features
    x = blk(x, resolution, shared_rel_pos_bias=rel_pos_bias)
  File "C:\stable-diffusion-webui\venvopt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User/.cache\torch\hub\intel-isl_MiDaS_master\midas\backbones\beit.py", line 102, in block_forward
    x = x + self.drop_path(self.gamma_1 * self.attn(self.norm1(x), resolution,
  File "C:\stable-diffusion-webui\venvopt\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Block' object has no attribute 'drop_path'

Time taken: 2 min. 4.8 sec.

A: 4.07 GB, R: 4.21 GB, Sys: 6.9/23.9883 GB (28.6%)

```
version: [v1.5.1-488-g0dc74545](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0dc74545c0b5510911757ed9f2be703aab58f014)  •  python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.39.0  •  checkpoint: [ec41bd2a82](https://google.com/search?q=ec41bd2a8271acde4ae81cac004d9f3300e7fb0870eae8cbfe0bbc4ef8e27f91)

**Comment by semjon00** [comment]
Hello! Thanks for reporting. This looks to be similar: https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/319
