### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'  | Even though it is installed

### ISSUE THREAD

**Issue by FoxTrotte** [thygate/stable-diffusion-webui-depthmap-script#329]
Hey, I created an anaconda environment for this, using python 3.10.

I ran pip install -r requirements.txt, I see it successfully installed Gradio, no errors there.

But when I run main.py, I have the following errors:

`(base) F:\Dossiers\Stable-Diffusion-Depth-Standalone>python main.py
DepthMap v0.4.3 (<none>) running in standalone mode!
Traceback (most recent call last):
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\main.py", line 39, in <module>
    import src.common_ui
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\common_ui.py", line 3, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'`

I'm using Windows 10, I have no idea why this might be happening. Running gradio from the environment works, so gradio is well installed.

Any ideas what might be causing this ?
Thanks !

**Comment by FoxTrotte** [comment]
Okay I was being stupid, I forgot to activate the conda environment after crreating it
