### ISSUE TITLE
ModuleNotFoundError: No module named 'timm' | Even though timm is installed

### ISSUE THREAD

**Issue by FoxTrotte** [thygate/stable-diffusion-webui-depthmap-script#330]
Hey ! I'm trying to use the standalone UI for this on my Windows10 machine, and I run into the following issue when running main.py:

`(depth) F:\Dossiers\Stable-Diffusion-Depth-Standalone>main.py
DepthMap v0.4.3 (<none>) running in standalone mode!
  The standalone mode is not on par with the stable-diffusion-webui mode.
  Some features may be missing or work differently. Please report bugs.

Traceback (most recent call last):
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\main.py", line 39, in <module>
    import src.common_ui
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\common_ui.py", line 6, in <module>
    from src import backbone, video_mode
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\video_mode.py", line 8, in <module>
    from src import core
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\core.py", line 26, in <module>
    from src.depthmap_generation import ModelHolder
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\depthmap_generation.py", line 13, in <module>
    from dmidas.dpt_depth import DPTDepthModel
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dmidas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dmidas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dmidas\backbones\beit.py", line 1, in <module>
    import timm
ModuleNotFoundError: No module named 'timm'`

Looking at the installation during the pip install -r requirements.txt, timm seems to install successfully. 
I tried uninstalling timm and reinstalling it with `timm~=0.6.12` but that does not fix the issue.

Any Idea what could be causing this ?

Thanks !

**Comment by semjon00** [comment]
Hello! This is weird... Could you please create a list of all the installed packages and check if timm is still installed? Maybe the issue happens because you install system-wide - you could try using venv. By the way the main branch just got updated to use a newer version of timm (0.9.2).

**Comment by FoxTrotte** [comment]
Okay, I started figured out what I was doing wrong: When launching main.py with just a `main.py` command, I had the ModuleNotFoundError: No module named 'timm' error. But when launching it with `python main.py`, it doesn't happen !!
