### ISSUE TITLE
Error completing request when generating video

### ISSUE THREAD

**Issue by semjon00** [thygate/stable-diffusion-webui-depthmap-script#355]
### Discussed in https://github.com/thygate/stable-diffusion-webui-depthmap-script/discussions/354

<div type='discussions-op-text'>

<sup>Originally posted by **vitalbuttering** October 12, 2023</sup>
Anyone can diagnose why i am getting this error when i try to generate video on Depth?

Error completing request
Arguments: (None, '300', '40', 1, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', False, 'mp4', '3') {}
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "I:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "I:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 590, in run_makevideo
    if len(fn_mesh) == 0 or not os.path.exists(fn_mesh):
TypeError: object of type 'NoneType' has no len()</div>

**Comment by graemeniedermayer** [comment]
It's so weird that that the last 3 issues are about NoneTypes but also seem unrelated.

```TypeError: object of type 'NoneType' has no len()```
Here
```TypeError: must be real number, not NoneType```
https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/352
```cannot unpack non-iterable NoneType object```
https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/353

Maybe an import dependency has recently changed.  fn_mesh path is so straightforward the only package that comes to mind is a bad ```gradio``` update, maybe try reverting to an older gradio? auto1111 will likely try update gradio during startup so this might be a little challenging.
