### ISSUE TITLE
NameError: name 'video_mesh_data' is not defined

### ISSUE THREAD

**Issue by blackneoo** [thygate/stable-diffusion-webui-depthmap-script#381]
Whenever i try to generate video i get this error, regardless of using the fast or slow mesh generation.

*** Error completing request
*** Arguments: ('outputs\\extras-images\\depthmap-0004-simple.obj', '90', '30', 1, '-0.015, 0.0, -0.05', '0.03, 0.03, 0.05, 0.03', False, 'mp4', '4') {}
    Traceback (most recent call last):
      File "C:\Users\lhusa\SD\stable-diffusion-webui-1.6.0\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\lhusa\SD\stable-diffusion-webui-1.6.0\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\lhusa\SD\stable-diffusion-webui-1.6.0\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 628, in run_makevideo
        fn_saved = run_3dphoto_videos(fn_mesh, basename, outpath, num_frames, num_fps, crop_border, vid_traj, x_shift_range,
      File "C:\Users\lhusa\SD\stable-diffusion-webui-1.6.0\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 509, in run_3dphoto_videos
        del video_mesh_data
    NameError: name 'video_mesh_data' is not defined

**Comment by blackneoo** [comment]
Now it is working using the slow mesh generation, however the fast still doesnt work, now it shows 

 Exception: This requires a 3D inpainted mesh generated by this extension.

when i try again it shows the old message

NameError: name 'video_mesh_data' is not defined

i don't know if this is intended, does video generation work with the fast mesh?
