### ISSUE TITLE
Extension incompatibiilty: sd-webui-GPT4V-Image-Captioner/lib    ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'

### ISSUE THREAD

**Issue by swumagic** [thygate/stable-diffusion-webui-depthmap-script#398]
Error loading script: depthmap.py  and      ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'

*** Error loading script: depthmap.py
    Traceback (most recent call last):
      File "J:\StableDiffusion\sdwebui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 8, in <module>
        from src import common_ui
      File "J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-depthmap-script\src\common_ui.py", line 6, in <module>
        from src import backbone, video_mode
      File "J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-depthmap-script\src\video_mode.py", line 8, in <module>
        from src import core
      File "J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 23, in <module>
        from src.depthmap_generation import ModelHolder
      File "J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-depthmap-script\src\depthmap_generation.py", line 21, in <module>
        from lib.multi_depth_model_woauxi import RelDepthModel
    ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'

---
*** Error loading script: depthmap_api.py
    Traceback (most recent call last):
      File "J:\StableDiffusion\sdwebui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap_api.py", line 16, in <module>
        from src.core import core_generation_funnel, run_makevideo
      File "J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 23, in <module>
        from src.depthmap_generation import ModelHolder
      File "J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-depthmap-script\src\depthmap_generation.py", line 21, in <module>
        from lib.multi_depth_model_woauxi import RelDepthModel
    ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'

**Comment by swumagic** [comment]
win11，SDWEBUI 1.7.0,PYTHON 3.10.11,

**Comment by swumagic** [comment]
Issue was that the sd-webui-GPT4V-Image-Captioner/lib folder was shadowing the Depthmap/lib folder.I changed the name of the "lib" folder in TokenMixer to "library" to solve this.
