### ISSUE TITLE
error at run script

### ISSUE THREAD

**Issue by popedead** [thygate/stable-diffusion-webui-depthmap-script#4]
hi, this is my error,, midas in repo, script in scripts

Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.54it/s]
DepthMap v0.1.0
device: cuda
Loading midas model weights ..
./models/midas/dpt_large-midas-2f21e586.pt
Error verifying pickled file from ./models/midas/dpt_large-midas-2f21e586.pt:
Traceback (most recent call last):
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\safe.py", line 76, in check_pt
with zipfile.ZipFile(filename) as z:
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1267, in init
self._RealGetContents()
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1334, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\safe.py", line 97, in load
check_pt(filename)
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\safe.py", line 89, in check_pt
unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Error completing request
Arguments: ('city', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 1, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, 0, 0, True, True, False, 1, False, False, False, '', 1, '', 0, '', True, True, False, 1.0, 2.0, 'a painting in', 'style', 'picture frame, portrait photo', None) {}
Traceback (most recent call last):
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\ui.py", line 185, in f
res = list(func(*args, **kwargs))
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\webui.py", line 55, in f
res = func(*args, **kwargs)
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\txt2img.py", line 45, in txt2img
processed = modules.scripts.scripts_txt2img.run(p, *args)
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\modules\scripts.py", line 297, in run
processed = script.run(p, *script_args)
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\scripts\depthmap.py", line 83, in run
model = DPTDepthModel(
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 105, in init
self.load(path)
File "C:\Users\popec\Documents\GitHub\stable-diffusion-webui\repositories\midas\midas\base_model.py", line 13, in load
if "optimizer" in parameters:
TypeError: argument of type 'NoneType' is not iterable

thanks

**Comment by thygate** [comment]
sounds like the downloaded checkpoint is corrupted ?

Try deleting the downloaded checkpoints in `/stable-diffusion-webui/models/midas/`
Delete `midas/dpt_large-midas-2f21e586.pt` there, and try running the script again, re-downloading the file.

I just verified the download link for that model, and it is ok. So try again after deleting that file.

**Comment by popedead** [comment]
very well you fixed it, thank you very much, and very good job, this is fantastic

**Comment by thygate** [comment]
you're welcome, easy fix.
