### ISSUE TITLE
depthmap.py startup error on load in A1111

### ISSUE THREAD

**Issue by alexjl90210** [thygate/stable-diffusion-webui-depthmap-script#418]
*** Error loading script: depthmap.py
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 704, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)

Depth Tab in UI doesn't load as it used to earlier this year.

Then I see a bunch of frozen load errors for the web ui in Colab.
Seen another loading issue page where it was suggested to change the timm module version 0.6.12
Any working depth map UIs for Colab available ?

**Comment by psyxodel** [comment]
yes, i have errors too and extension don't work =(
![Снимок экрана 2025-01-11 093930](https://github.com/user-attachments/assets/17476227-86ec-4dac-9ec5-d80fe16cfaf9)
![Снимок экрана 2025-01-11 094055](https://github.com/user-attachments/assets/816d0e2a-0736-413d-ae55-594ef7b62f1b)

**Comment by DarkoSM** [comment]
Same trouble here. Found on reddit that someone fixed this problem by copying some files from old A1111 to new one. But he never shared package. Is there an official workaround?
