### ISSUE TITLE
*** Error loading script: depthmap.py ImportError: fontconfig not found

### ISSUE THREAD

**Issue by stf6** [thygate/stable-diffusion-webui-depthmap-script#426]
unable to install in sagemaker studio lab
complete error message : 

*** Error loading script: depthmap.py
    Traceback (most recent call last):
      File "/home/studio-lab-user/asd/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/studio-lab-user/asd/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/studio-lab-user/asd/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 8, in <module>
        from src import common_ui
      File "/home/studio-lab-user/asd/extensions/stable-diffusion-webui-depthmap-script/src/common_ui.py", line 6, in <module>
        from src import backbone, video_mode
      File "/home/studio-lab-user/asd/extensions/stable-diffusion-webui-depthmap-script/src/video_mode.py", line 8, in <module>
        from src import core
      File "/home/studio-lab-user/asd/extensions/stable-diffusion-webui-depthmap-script/src/core.py", line 27, in <module>
        from inpaint.mesh import write_mesh, read_mesh, output_3d_photo
      File "/home/studio-lab-user/asd/extensions/stable-diffusion-webui-depthmap-script/inpaint/mesh.py", line 12, in <module>
        from vispy import scene, io
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/__init__.py", line 27, in <module>
        from .util import config, set_log_level, keys, sys_info  # noqa
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/util/__init__.py", line 14, in <module>
        from . import fonts       # noqa
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
        from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/util/fonts/_triage.py", line 11, in <module>
        from ._freetype import _load_glyph
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/util/fonts/_freetype.py", line 16, in <module>
        from ...ext.fontconfig import find_font
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/ext/fontconfig.py", line 12, in <module>
        raise ImportError('fontconfig not found')
    ImportError: fontconfig not found

---
*** Error loading script: depthmap_api.py
    Traceback (most recent call last):
      File "/home/studio-lab-user/asd/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/studio-lab-user/asd/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/studio-lab-user/asd/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap_api.py", line 16, in <module>
        from src.core import core_generation_funnel, run_makevideo
      File "/home/studio-lab-user/asd/extensions/stable-diffusion-webui-depthmap-script/src/core.py", line 27, in <module>
        from inpaint.mesh import write_mesh, read_mesh, output_3d_photo
      File "/home/studio-lab-user/asd/extensions/stable-diffusion-webui-depthmap-script/inpaint/mesh.py", line 12, in <module>
        from vispy import scene, io
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/__init__.py", line 27, in <module>
        from .util import config, set_log_level, keys, sys_info  # noqa
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/util/__init__.py", line 14, in <module>
        from . import fonts       # noqa
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
        from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/util/fonts/_triage.py", line 11, in <module>
        from ._freetype import _load_glyph
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/util/fonts/_freetype.py", line 16, in <module>
        from ...ext.fontconfig import find_font
      File "/home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages/vispy/ext/fontconfig.py", line 12, in <module>
        raise ImportError('fontconfig not found')
    ImportError: fontconfig not found

**Comment by chenxuan13** [comment]
i have the same bug, but can"t sovle it? how can i do this

**Comment by semjon00** [comment]
Ok, found the isolation issue. There is an issue with another project - vispy - which fails to import. Regardless of this failure, it should not cascade to this project and break it, if you are not using inpainting (slow mesh thing). So I tweaked the code, now failing vispy should not cause issues for the rest of the functionality.
