### ISSUE TITLE
Generate stereoscopic (3D) image(s) An error occurs during use.

### ISSUE THREAD

**Issue by turugi-ni** [thygate/stable-diffusion-webui-depthmap-script#449]
Generate stereoscopic (3D) image(s) If you try to create a side-by-side and red-cyan-anaglyph image using
To create a public link, set `share=True` in `launch()`.
Startup time: 12.4s (load scripts: 6.7s, create ui: 1.3s, gradio launch: 2.6s, app_started_callback: 1.7s).
[Tiled Diffusion] ignore tiling when there's only 1 tile or nothing to do :)
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.06it/s]
[Tiled VAE]: the input size is tiny and unnecessary to tile.
DepthMap v0.4.7 (deea8407)
device: cuda
Loading model(s) ..
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing output(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]wholeImage being processed in : 1120
Adjust factor is: 1.590909090909091
Selecting patches ...
Target resolution:  (3564, 3564, 3)
Resulting depthmap resolution will be : (512, 512)
patches to process: 30
         processing patch 0 / 29 | [  1   1 416 416]
         processing patch 1 / 29 | [ 49   1 416 416]
         processing patch 2 / 29 | [ 49  49 416 416]
         processing patch 3 / 29 | [101   5 409 409]
         processing patch 4 / 29 | [101  53 409 409]
         processing patch 5 / 29 | [ 12  60 394 394]
         processing patch 6 / 29 | [ 75 123 366 366]
         processing patch 7 / 29 | [144 144 323 323]
         processing patch 8 / 29 | [  3   3 315 315]
         processing patch 9 / 29 | [  3  51 315 315]
         processing patch 10 / 29 | [  3 100 315 315]
         processing patch 11 / 29 | [ 51   3 315 315]
         processing patch 12 / 29 | [100   3 315 315]
         processing patch 13 / 29 | [148   3 315 315]
         processing patch 14 / 29 | [196  51 315 315]
         processing patch 15 / 29 | [218 121 272 272]
         processing patch 16 / 29 | [232 184 244 244]
         processing patch 17 / 29 | [  2  50 222 222]
         processing patch 18 / 29 | [ 50   2 222 222]
         processing patch 19 / 29 | [ 98   2 222 222]
         processing patch 20 / 29 | [146   2 222 222]
         processing patch 21 / 29 | [195   2 222 222]
         processing patch 22 / 29 | [ 16 112 193 193]
         processing patch 23 / 29 | [ 27 172 172 172]
         processing patch 24 / 29 | [ 97   0 129 129]
         processing patch 25 / 29 | [145   0 129 129]
         processing patch 26 / 29 | [193   0 129 129]
         processing patch 27 / 29 | [241   0 129 129]
         processing patch 28 / 29 | [290   0 129 129]
         processing patch 29 / 29 | [338   0 129 129]
*** Error completing request
*** Arguments: ('task(bywntaz3o0cd64s)', <gradio.routes.Request object at 0x0000013D17E59AE0>, 'masterpiece, \nday, front view, upper_body, \n1girl, standing, embarrass, looking_at_viewer, huge breasts, areola, nipples, nude, ', 'easynegative, antiBlurV2, (bad_prompt_version2:0.8), bad-hands-5, negative_hand, ugly face, signature, watermark, amputee, censored, text, ', [], 1, 1, 7, 512, 512, True, 0.5, 1, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 6, 20, 'DPM++ 2M', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, True, 'MultiDiffusion', True, True, 512, 512, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 'DemoFusion', True, 128, 64, 4, 2, False, 10, 1, 1, 64, False, True, 3, 1, 1, True, 3072, 192, True, True, True, False, <scripts.animatediff_ui.AnimateDiffProcess object at 0x0000013D17E80E80>, UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), False, '', 0.5, True, False, '', 'Lerp', False, True, 0, 1, 0, 'Version 2', 1.2, 0.9, 0, 0.5, 0, 1, 1.4, 0.2, 0, 0.5, 0, 1, 1, 1, 0, 0.5, 0, 1, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, True, False, False, False, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, False, False, False, '#000000', False, None, None, False, None, None, False, None, None, False, 50, True, False, 0, 'Range', 1, 'GPU', True, False, False, False, True, 0, 448, False, 448, False, False, 3, False, 3, True, 3, False, 'Horizontal', False, False, 'u2net', False, True, True, False, -0.1, 2.5, 'polylines_sharp', ['left-right', 'red-cyan-anaglyph'], 1, 0, False, '∯boost∯clipdepth∯clipdepth_far∯clipdepth_mode∯clipdepth_near∯compute_device∯do_output_depth∯gen_normalmap∯gen_rembg∯gen_simple_mesh∯gen_stereo∯model_type∯net_height∯net_size_match∯net_width∯normalmap_invert∯normalmap_post_blur∯normalmap_post_blur_kernel∯normalmap_pre_blur∯normalmap_pre_blur_kernel∯normalmap_sobel∯normalmap_sobel_kernel∯output_depth_combine∯output_depth_combine_axis∯output_depth_invert∯pre_depth_background_removal∯rembg_model∯save_background_removal_masks∯save_outputs∯simple_mesh_occlude∯simple_mesh_spherical∯stereo_balance∯stereo_divergence∯stereo_fill_algo∯stereo_modes∯stereo_offset_exponent∯stereo_separation∯tiling_mode') {}
    Traceback (most recent call last):
      File "D:\Touls\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Touls\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Touls\stable-diffusion-webui\modules\txt2img.py", line 106, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
      File "D:\Touls\stable-diffusion-webui\modules\scripts.py", line 773, in run
        processed = script.run(p, *script_args)
      File "D:\Touls\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 57, in run
        info = create_infotext(
      File "D:\Touls\stable-diffusion-webui\modules\processing.py", line 774, in create_infotext
        "Schedule type": p.scheduler,
    AttributeError: 'Processed' object has no attribute 'scheduler'

---
  0%|                                                                                            | 0/1 [00:16<?, ?it/s]
and cannot create an image.

**Comment by semjon00** [comment]
Hello and thanks for reporting! What WebUI version do you use?

**Comment by turugi-ni** [comment]
The version of the WebUI is v1.9.4.

**Comment by semjon00** [comment]
Please update one more time, maybe it is now fixed. Please write your results.
