### ISSUE TITLE
[REQUEST] Implementing Depthmap Anything V2 model?

### ISSUE THREAD

**Issue by eyeEmotion** [thygate/stable-diffusion-webui-depthmap-script#450]
Hi,

is there any intention of implementing the new Depth Anything v2 model? (Base and Large).

I'm currently using it via cmd-prompt, and it has a lot more detail, and is a little bit faster at generating depthmaps too. Although in certain areas, it does take a step backwards though in comparison to v1. But still a vast improvement overal.

Cheers.

PS: sorry, I don't know how to put labels on there requests.

**Comment by petermg** [comment]
> Hi,
> 
> is there any intention of implementing the new Depth Anything v2 model? (Base and Large).
> 
> I'm currently using it via cmd-prompt, and it has a lot more detail, and is a little bit faster at generating depthmaps too. Although in certain areas, it does take a step backwards though in comparison to v1. But still a vast improvement overal.
> 
> Cheers.
> 
> PS: sorry, I don't know how to put labels on there requests.

I'm also hoping for this!

**Comment by semjon00** [comment]
I am hoping somwbody could impöement it. I am busy currently.

**Comment by graemeniedermayer** [comment]
If @petermg @eyeEmotion @semjon00 wanted to test it out #458 in pull request. Might need some finessing but it seems to be working.

**Comment by petermg** [comment]
> If @petermg @eyeEmotion @semjon00 wanted to test it out #458 in pull request. Might need some finessing but it seems to be working.

Awesome! How do I install it instead of the main branch?

**Comment by petermg** [comment]
Thought I got it installed, it shows up as an option but it gives the error:

ModuleNotFoundError: No module named 'depth_anything_v2'

**Comment by petermg** [comment]
Here's the full error:

Please report this issue [here](https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues). Make sure to provide the full stacktrace:
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-normalmap-script\src\common_ui.py", line 548, in run_generate
    input_i, type, result = next(gen_obj)
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-normalmap-script\src\core.py", line 329, in core_generation_funnel
    raise e
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-normalmap-script\src\core.py", line 130, in core_generation_funnel
    model_holder.ensure_models(inp[go.MODEL_TYPE], device, inp[go.BOOST], inp[go.TILING_MODE])
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-normalmap-script\src\depthmap_generation.py", line 68, in ensure_models
    self.load_models(model_type, device, boost, tiling_mode)
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-normalmap-script\src\depthmap_generation.py", line 233, in load_models
    from depth_anything_v2.depth_anything_v2.dpt import DepthAnythingV2
ModuleNotFoundError: No module named 'depth_anything_v2'

**Comment by graemeniedermayer** [comment]
You might need to do a extra `git pull`. 

If not check that in the extension file `stable-diffusion-webui-depthmap-script` folder there is a `depth_anything_v2` folder that isn't empty. 

I might have also made a pathing error somewhere.

**Comment by petermg** [comment]
> You might need to do a extra `git pull`.
> 
> If not check that in the extension file `stable-diffusion-webui-depthmap-script` folder there is a `depth_anything_v2` folder that isn't empty.
> 
> I might have also made a pathing error somewhere.

Still getting the error. Here is what that folder contains on my system:
![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/20764493/23d410db-3ac8-4620-b6ca-4340b2f8459c)


also here is the error:
![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/20764493/a80c8871-28b5-4e51-b603-9e46530febd3)

**Comment by petermg** [comment]
and when I did a git pull

![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/20764493/83296e3f-75bc-4d49-b6b1-43d244fff577)

**Comment by graemeniedermayer** [comment]
Thank you for all the information! That is how the folder should look, so I'm a little confused. I made some small edits, but I'm not confident they'll fix it. I'll have to think about it more.

If you have any other extensions that use depth_anything_v2 you could try changing the line to `from depth_anything_v2.dpt import  DepthAnythingV2` and seeing if there's any change. You could also try temporarily turning off all the other extensions. 

My import structure is very similar to the marigold import. Does marigold work for you?

**Comment by petermg** [comment]
> Thank you for all the information! That is how the folder should look, so I'm a little confused. I made some small edits, but I'm not confident they'll fix it. I'll have to think about it more.
> 
> If you have any other extensions that use depth_anything_v2 you could try changing the line to `from depth_anything_v2.dpt import DepthAnythingV2` and seeing if there's any change. You could also try temporarily turning off all the other extensions.
> 
> My import structure is very similar to the marigold import. Does marigold work for you?

Yes Marigold works no problem. Maybe I installed it wrong? I went to EXTENSIONS tab, UNCHECKED the official depth map extension and installed this one via INSTALL FROM URL and used this as the url:
https://github.com/graemeniedermayer/stable-diffusion-webui-normalmap-script
and for branch put depthanything_v2
It says it's installed. But maybe I did something wrong? Here is my extension tab.
![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/20764493/4182aa01-4b08-4898-944d-12adba06104a)

**Comment by petermg** [comment]
Ok so here is something weird, BEFORE I update to the update you just did, I have the DEPTH Tab as seen here:

![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/20764493/33a92c08-1a7f-4363-a552-ac96a5a7c7f1)

But after updating to your update just now, it's totally gone!

![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/20764493/a9fc0a8e-1b11-4973-8369-ab12519ca094)

**Comment by petermg** [comment]
ok I deleted the extensions inside the folder and installed just your version and the depth tab is back but still the same exact error. I'll see if I can figure out how to do what you mentioned about changing the line to from depth_anything_v2.dpt import DepthAnythingV2 and seeing if there's any change.

**Comment by petermg** [comment]
I am unable to find the file "depth_anything_v2.dpt". Should I have it somewhere?

**Comment by graemeniedermayer** [comment]
the problem import line is in `src/depthmap_generation.py` file. 

Oh I forgot to push my last two updates.

**Comment by petermg** [comment]
> the problem import line is in `src/depthmap_generation.py` file.
> 
> Oh I forgot to push my last updates.

THAT WORKED!!! 
*HOWEVER* I did end up needing to manually delete the original installation of the extension because when I just updated it, the "Depth" tab went away again. When I deleted the folder manually and reinstalled the extension, then it worked.

**Comment by petermg** [comment]
So for some reason YOUR version is working BETTER than if I just use depth anything v2 from here
https://github.com/DepthAnything/Depth-Anything-V2
from the command line!? The one from there using the command line produces a depth map with only 8 bit precision, resulting in stair stepping when trying to apply this to a 2D plane, for example:
![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/20764493/8e299882-2953-49a1-a944-daac2c07ec33)
You can see the stair stepping in that one, which was done by the command line version, and produces a depth map of only 8 bit integer.
HOWEVER, when I process the same image using your extension of Depth Anything V2 the result I get is:
![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/20764493/58723a41-81e1-494a-b4fa-3bf8840f952b)
Do you have any idea why this is? Like what command or line in what python script changes the bit depth accuracy?  Also, not that it's needed but is it possible to increase the bit depth precision even more just to see if it would make any difference?

**Comment by graemeniedermayer** [comment]
Awesome! A lot of scripts downsample to 8bit arrays while saving images. I'm not sure why they do this. 

For precision at a certain point it probably just makes more sense to work with pointclouds or float arrays because then they keep more information. This didn't make sense earlier because there wasn't enough detail anyways, but I think monodepth is starting to get precise enough that it might make sense to think about switching out of images for 3d work. 

(the line of code in `run.py` that down samples the array)
```
depth = (depth - depth.min()) / (depth.max() - depth.min()) * 255.0
depth = depth.astype(np.uint8)
if args.grayscale:
     depth = np.repeat(depth[..., np.newaxis], 3, axis=-1)
else:
     depth = (cmap(depth)[:, :, :3] * 255)[:, :, ::-1].astype(np.uint8)
```

**Comment by petermg** [comment]
> Awesome! A lot of scripts downsample to 8bit arrays while saving images. I'm not sure why they do this.
> 
> For precision at a certain point it probably just makes more sense to work with pointclouds or float arrays because then they keep more information. This didn't make sense earlier because there wasn't enough detail anyways, but I think monodepth is starting to get precise enough that it might make sense to think about switching out of images for 3d work.
> 
> (the line of code in `run.py` that down samples the array)
> 
> ```
> depth = (depth - depth.min()) / (depth.max() - depth.min()) * 255.0
> depth = depth.astype(np.uint8)
> if args.grayscale:
>      depth = np.repeat(depth[..., np.newaxis], 3, axis=-1)
> else:
>      depth = (cmap(depth)[:, :, :3] * 255)[:, :, ::-1].astype(np.uint8)
> ```

Thank you, how can I modify this so that I can increase the precision?

**Comment by petermg** [comment]
> Awesome! A lot of scripts downsample to 8bit arrays while saving images. I'm not sure why they do this.
> 
> For precision at a certain point it probably just makes more sense to work with pointclouds or float arrays because then they keep more information. This didn't make sense earlier because there wasn't enough detail anyways, but I think monodepth is starting to get precise enough that it might make sense to think about switching out of images for 3d work.
> 
> (the line of code in `run.py` that down samples the array)
> 
> ```
> depth = (depth - depth.min()) / (depth.max() - depth.min()) * 255.0
> depth = depth.astype(np.uint8)
> if args.grayscale:
>      depth = np.repeat(depth[..., np.newaxis], 3, axis=-1)
> else:
>      depth = (cmap(depth)[:, :, :3] * 255)[:, :, ::-1].astype(np.uint8)
> ```

Ok so I changed to this:

```
 for k, filename in enumerate(filenames):
        print(f'Progress {k+1}/{len(filenames)}: {filename}')
        
        raw_image = cv2.imread(filename)
        
        depth = depth_anything.infer_image(raw_image, args.input_size)
        
        depth = (depth - depth.min()) / (depth.max() - depth.min()) * 2048.0
        depth = depth.astype(np.uint16)
        
        if args.grayscale:
            depth = np.repeat(depth[..., np.newaxis], 3, axis=-1)
        else:
            depth = (cmap(depth)[:, :, :3] * 2048)[:, :, ::-1].astype(np.uint16)
        
        if args.pred_only:
            cv2.imwrite(os.path.join(args.outdir, os.path.splitext(os.path.basename(filename))[0] + '.png'), depth)
        else:
            split_region = np.ones((raw_image.shape[0], 50, 3), dtype=np.uint16) * 2048
            combined_result = cv2.hconcat([raw_image, split_region, depth])
            
            cv2.imwrite(os.path.join(args.outdir, os.path.splitext(os.path.basename(filename))[0] + '.png'), combined_result)
```

from:

```
    for k, filename in enumerate(filenames):
        print(f'Progress {k+1}/{len(filenames)}: {filename}')
        
        raw_image = cv2.imread(filename)
        
        depth = depth_anything.infer_image(raw_image, args.input_size)
        
        depth = (depth - depth.min()) / (depth.max() - depth.min()) * 255.0
        depth = depth.astype(np.uint8)
        
        if args.grayscale:
            depth = np.repeat(depth[..., np.newaxis], 3, axis=-1)
        else:
            depth = (cmap(depth)[:, :, :3] * 255)[:, :, ::-1].astype(np.uint8)
        
        if args.pred_only:
            cv2.imwrite(os.path.join(args.outdir, os.path.splitext(os.path.basename(filename))[0] + '.png'), depth)
        else:
            split_region = np.ones((raw_image.shape[0], 50, 3), dtype=np.uint8) * 255
            combined_result = cv2.hconcat([raw_image, split_region, depth])
            
            cv2.imwrite(os.path.join(args.outdir, os.path.splitext(os.path.basename(filename))[0] + '.png'), combined_result)
```


Now it creates files that are 16 bit but are very dark, look almost black, until I open them in GIMP and use the LEVELS tool. I also increase the precision in GIMP as high as it will go BEFORE I save the file, but I don't think I should HAVE to do this but it turns out better when I do. I'm crazy impressed with this so far. Would be nice to be able to automate this so that I can process multiple at a time. Here is my current command line that I run

python run.py --encoder vitl --img-path Inputpics --outdir Outputpics --pred-only --grayscale --input-size 1200

Increasing the input size makes a **NOTICEABLE DIFFERENCE!**

**Comment by petermg** [comment]
> Oh instead of 2048 you should be able to use 255*255 or 65025. This should make them less dark. The input size is interesting I should double check that I implemented that correctly.

**THANKS!!** that works *PERFECTLY!!!*

**Comment by petermg** [comment]
I don't really know much about the whole "BOOST" and "TILING" options, they always seem to make things WORSE when I've tried to use them, but at least for Depth Anything V2, I think what IS useful if you could implement it in this plugin version of it, is changing the input size, like manually selecting it on the sliders and also selecting the native input size checkbox.

**Comment by noobtoob4lyfe** [comment]
Now that there has been so much progress in this thread towards installing and using without errors, would it be possible to give a quick guide of how to install this for a less advanced user like myself?  I would really love to give this a try.

**Comment by petermg** [comment]
> Now that there has been so much progress in this thread towards installing and using without errors, would it be possible to give a quick guide of how to install this for a less advanced user like myself? I would really love to give this a try.

https://www.reddit.com/r/StableDiffusion/comments/1e02w8b/how_to_use_depth_anything_v2_in_automatic1111s/
