### ISSUE TITLE
DeptMap Standalone: No Video generation

### ISSUE THREAD

**Issue by Five-Birds** [thygate/stable-diffusion-webui-depthmap-script#454]
I installed the standalone Version of the script and all its requirements. Depthmaps and 3d inpainetd meshs are working, but i cannot render a video out of the results. The following error occurs:

Loading mesh ..
Traceback (most recent call last):
  File "D:\Depthmap\stable-diffusion-webui-depthmap-script\src\core.py", line 512, in run_3dphoto_videos
    vispy.use(app='PyQt5')
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\util\wrappers.py", line 93, in use
    use_app(app)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 47, in __init__
    self._use(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 233, in _use
    __import__(mod_name, globals(), level=1)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_pyqt5.py", line 32, in <module>
    from . import _qt  # noqa
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_qt.py", line 91, in <module>
    _check_imports('PyQt5')
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_qt.py", line 63, in _check_imports
    raise RuntimeError("Refusing to import %s because %s is already "
RuntimeError: Refusing to import PyQt5 because PyQt6.QtCore is already imported.

Trying an alternative...
WARNING: pyqt5 already imported, cannot switch to pyqt5
On PyQt5
Traceback (most recent call last):
  File "D:\Depthmap\stable-diffusion-webui-depthmap-script\src\core.py", line 512, in run_3dphoto_videos
    vispy.use(app='PyQt5')
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\util\wrappers.py", line 93, in use
    use_app(app)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 47, in __init__
    self._use(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 233, in _use
    __import__(mod_name, globals(), level=1)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_pyqt5.py", line 32, in <module>
    from . import _qt  # noqa
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_qt.py", line 91, in <module>
    _check_imports('PyQt5')
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_qt.py", line 63, in _check_imports
    raise RuntimeError("Refusing to import %s because %s is already "
RuntimeError: Refusing to import PyQt5 because PyQt6.QtCore is already imported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Depthmap\stable-diffusion-webui-depthmap-script\src\core.py", line 523, in run_3dphoto_videos
    vispy.use(app=u)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\util\wrappers.py", line 93, in use
    use_app(app)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 47, in __init__
    self._use(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 263, in _use
    self._backend = self.backend_module.ApplicationBackend()
AttributeError: module 'vispy.app.backends._pyqt5' has no attribute 'ApplicationBackend'

WARNING: pyqt5 already imported, cannot switch to pyqt6
On PyQt6
Traceback (most recent call last):
  File "D:\Depthmap\stable-diffusion-webui-depthmap-script\src\core.py", line 512, in run_3dphoto_videos
    vispy.use(app='PyQt5')
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\util\wrappers.py", line 93, in use
    use_app(app)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 47, in __init__
    self._use(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 233, in _use
    __import__(mod_name, globals(), level=1)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_pyqt5.py", line 32, in <module>
    from . import _qt  # noqa
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_qt.py", line 91, in <module>
    _check_imports('PyQt5')
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_qt.py", line 63, in _check_imports
    raise RuntimeError("Refusing to import %s because %s is already "
RuntimeError: Refusing to import PyQt5 because PyQt6.QtCore is already imported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Depthmap\stable-diffusion-webui-depthmap-script\src\core.py", line 523, in run_3dphoto_videos
    vispy.use(app=u)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\util\wrappers.py", line 93, in use
    use_app(app)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 47, in __init__
    self._use(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 263, in _use
    self._backend = self.backend_module.ApplicationBackend()
AttributeError: module 'vispy.app.backends._pyqt6' has no attribute 'ApplicationBackend'

On egl
Traceback (most recent call last):
  File "D:\Depthmap\stable-diffusion-webui-depthmap-script\src\core.py", line 512, in run_3dphoto_videos
    vispy.use(app='PyQt5')
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\util\wrappers.py", line 93, in use
    use_app(app)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 47, in __init__
    self._use(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 233, in _use
    __import__(mod_name, globals(), level=1)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_pyqt5.py", line 32, in <module>
    from . import _qt  # noqa
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_qt.py", line 91, in <module>
    _check_imports('PyQt5')
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\backends\_qt.py", line 63, in _check_imports
    raise RuntimeError("Refusing to import %s because %s is already "
RuntimeError: Refusing to import PyQt5 because PyQt6.QtCore is already imported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Depthmap\stable-diffusion-webui-depthmap-script\src\core.py", line 523, in run_3dphoto_videos
    vispy.use(app=u)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\util\wrappers.py", line 93, in use
    use_app(app)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 47, in __init__
    self._use(backend_name)
  File "C:\Users\Five-\AppData\Local\Programs\Python\Python310\lib\site-packages\vispy\app\application.py", line 240, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "EGL":
EGL library not found

**Comment by LilChrisHe** [comment]
same here
