### ISSUE TITLE
unfortunately I am having a problem leading the script. "No such file or directory: './externals/Next_ViT/classification/nextvit.py"

### ISSUE THREAD

**Issue by amerqad** [thygate/stable-diffusion-webui-depthmap-script#57]
i am getting this error when i start the Web UI

Error loading script: depthmap.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 35, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 21, in <module>
    from .backbones.next_vit import (
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui\repositories\midas\midas\backbones\next_vit.py", line 8, in <module>
    file = open("./externals/Next_ViT/classification/nextvit.py", "r")
FileNotFoundError: [Errno 2] No such file or directory: './externals/Next_ViT/classification/nextvit.py'

**Comment by thygate** [comment]
See https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/55

**Comment by thygate** [comment]
Should be fixed in latest version.
