### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by benjamin-bertram** [thygate/stable-diffusion-webui-depthmap-script#58]
I use the script on a macbook pro with an apple m1max chip, 32 GB Ram. I updated the script to the latest version, tried different models and tried to compute it on GPU or CPU, I always end up with 

"AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'"

Does the script work on a mac? The Automatic1111 webui does work so far.

**Comment by thygate** [comment]
I'm not sure atm. I will have to investigate, do you have a stack trace for me ?

**Comment by benjamin-bertram** [comment]
I tried it now without boost which works fine. Now just the res101 throws an error: 

```
DepthMap v0.3.1
device: cpu
Loading model weights from  ./models/leres/res101.pth
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

With boost I get the following message.
Stack trace:

```
DepthMap v0.3.1
device: cpu
Loading model weights from  ./models/leres/res101.pth
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=1280x720 at 0x378CDFC70>, None, '', '', 1, 4, 384, 384, False, False, True, True, True, True, False, 1, False, False, 6.4, 38.5, 2, 0) {}
Traceback (most recent call last):
  File "/Users/benjaminbertram/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/Users/benjaminbertram/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/Users/benjaminbertram/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 567, in run_generate
    outputs = run_depthmap(None, outpath, imageArr, imageNameArr, compute_device, model_type, net_width, net_height, match_size, invert_depth, boost, save_depth, show_depth, show_heat, combine_output, combine_output_axis, gen_stereo, gen_anaglyph, stereo_ipd, stereo_size, stereo_fill, stereo_balance)
  File "/Users/benjaminbertram/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 228, in run_depthmap
    opt = MyTestOptions().parse()
  File "/Users/benjaminbertram/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1223, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/Users/benjaminbertram/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```

**Comment by thygate** [comment]
I just made a new commit with changes, try the latest version, I've removed those lines causing the error shown in the stack trace as they were redundant. Is boost working now ? (with something else than res101)

I did not increment the version number.

**Comment by benjamin-bertram** [comment]
Thank you for working on this so fast! 
It does not work, as I got now an assertion error:

```
DepthMap v0.3.1
device: cpu
Loading model weights from  ./models/midas/dpt_large-midas-2f21e586.pt
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=1280x720 at 0x2989B0040>, None, '', '', 0, 0, 384, 384, False, False, True, True, True, False, True, 1, False, False, 6.4, 38.5, 2, 0) {}
Traceback (most recent call last):
  File "/Users/benjaminbertram/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/Users/benjaminbertram/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/Users/benjaminbertram/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 567, in run_generate
    outputs = run_depthmap(None, outpath, imageArr, imageNameArr, compute_device, model_type, net_width, net_height, match_size, invert_depth, boost, save_depth, show_depth, show_heat, combine_output, combine_output_axis, gen_stereo, gen_anaglyph, stereo_ipd, stereo_size, stereo_fill, stereo_balance)
  File "/Users/benjaminbertram/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 231, in run_depthmap
    pix2pixmodel = Pix2Pix4DepthModel(opt)
  File "/Users/benjaminbertram/stable-diffusion-webui/repositories/BoostingMonocularDepth/pix2pix/models/pix2pix4depth_model.py", line 63, in __init__
    self.netG = networks.define_G(opt.input_nc, opt.output_nc, 64, 'unet_1024', 'none',
  File "/Users/benjaminbertram/stable-diffusion-webui/repositories/BoostingMonocularDepth/pix2pix/models/networks.py", line 167, in define_G
    return init_net(net, init_type, init_gain, gpu_ids)
  File "/Users/benjaminbertram/stable-diffusion-webui/repositories/BoostingMonocularDepth/pix2pix/models/networks.py", line 112, in init_net
    assert(torch.cuda.is_available())
AssertionError
```

**Comment by thygate** [comment]
It's in the boost repo itself, it would still seem to be cuda dependent even though it can run on cpu. 

You could try removing that assert line
File "/Users/benjaminbertram/stable-diffusion-webui/repositories/BoostingMonocularDepth/pix2pix/models/networks.py", line 112, in init_net
    assert(torch.cuda.is_available())

I will be pulling all dependencies locally in a future version of the extension so i can edit them..

**Comment by benjamin-bertram** [comment]
This is the stack trace for res101 (without boos):

DepthMap v0.3.1
device: cpu
Loading model weights from  ./models/leres/res101.pth
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.e

**Comment by thygate** [comment]
Only CPU or CUDA are supported. Good to know it's now working on CPU too without any CUDA device.

For the res101 problem, I just made another commit with a small adjustment that might solve the problem, not sure..

**Comment by benjamin-bertram** [comment]
Thanks it worked! Thank you very much for the fast response and solving the problem :)
