### ISSUE TITLE
Unable to load script

### ISSUE THREAD

**Issue by aiqng1q** [thygate/stable-diffusion-webui-depthmap-script#61]
JSONDecodeError: Expecting value: line 8 column 1 (char 7)

**Comment by thygate** [comment]
When doing what, how ? stack trace ?

**Comment by thygate** [comment]
Please see https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/55

**Comment by gulopbr** [comment]
At least for me it gives the following error:

Traceback (most recent call last):
  File "C:\Users\gulop\Desktop\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\gulop\Desktop\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\gulop\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 35, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "C:\Users\gulop\Desktop\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "C:\Users\gulop\Desktop\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 21, in <module>
    from .backbones.next_vit import (
  File "C:\Users\gulop\Desktop\stable-diffusion-webui\repositories\midas\midas\backbones\next_vit.py", line 8, in <module>
    file = open("./externals/Next_ViT/classification/nextvit.py", "r")
FileNotFoundError: [Errno 2] No such file or directory: './externals/Next_ViT/classification/nextvit.py'

**Comment by thygate** [comment]
See See https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/55

**Comment by thygate** [comment]
Should be fixed in latest version.
