### ISSUE TITLE
timm.models.beit error on colab

### ISSUE THREAD

**Issue by mykeehu** [thygate/stable-diffusion-webui-depthmap-script#74]
I installed the script on colab, but on reboot I got this error on version 0.3.2:

Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/midas/backbones/beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

I put these two lines in install.py, but it didn't help:
if not launch.is_installed("timm"):
    launch.run_pip("install timm", "timm requirement for depthmap script")

How can I use the script on colab?

**Comment by thygate** [comment]
Can you try `pip install --force-reinstall timm==0.6.12`

**Comment by mykeehu** [comment]
The timm installation was successful, but I got another problem:

```
/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
No module 'xformers'. Proceeding without it.
Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 14, in <module>
    from numba import njit, prange
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

**Comment by mykeehu** [comment]
After I put these two lines at the end of install.py:

```
launch.run_pip("install --force-reinstall timm==0.6.12", "timm requirement for depthmap script")
launch.run_pip("install scipy", "scipy requirement for depthmap script")
```
I got this error:

```
Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 14, in <module>
    from numba import njit, prange
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

**Comment by G-force78** [comment]
For automatic1111 WebUI I had to change the versions in requirement file and requirement versions to the one mentioned above

**Comment by mykeehu** [comment]
I'm out of colab for today, but I'll check this one out next time.

**Comment by thygate** [comment]
seems like a package version incompatibility with numba ..

You can remove the numba imports, remove the lines that start with @njit and replace the prange with range, only the stereo image generation will be much much slower ..

I will have to investigate further ..

**Comment by rockerBOO** [comment]
I was getting this error as well, and running what @aluuuanefields suggested got it working. 

Specifically (using the venv) ran this: 

```
pip install --force-reinstall timm==0.6.12
pip install numba==0.56.2
```

Both are required, as the first didn't work as well.

**Comment by Harvester62** [comment]
For the first time ever I got the error below at startup in SD Web UI by AUTOMATIC1111. The current versions of the above mentioned two libraries installed in SDWUI (Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8) are respectively timm-0.4.12 and numba-0.56.4, 

Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "C:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "C:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "C:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

**Comment by mykeehu** [comment]
> Both are required, as the first didn't work as well.
This unfortunately didn't help Colab, it crashed WebUI with torch errors.
