### ISSUE TITLE
Can't generate 3D inpainted mesh and demo videos

### ISSUE THREAD

**Issue by videoprice** [thygate/stable-diffusion-webui-depthmap-script#75]
any solutions?

DepthMap v0.3.4
device: cuda
Loading model weights from  ./models/leres/res101.pth
Computing depthmap(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.31it/s]
Done.
Running 3D Photo Inpainting ..
Downloading https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth to ./models/3dphoto/edge_model.pth
All done.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x247F706ADD0>, None, '', '', 0, 0, 512, 512, True, False, False, True, True, False, True, 1, False, False, 2.5, 4, 0, False, 0, 1, True, 0, 2) {}
Traceback (most recent call last):
  File "Q:\test\sd_new\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 506, in run_3dphoto
    download_file(edgemodel_path,"https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth")
  File "Q:\test\sd_new\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1225, in download_file
    torch.hub.download_url_to_file(url, filename)
  File "Q:\test\sd_new\venv\lib\site-packages\torch\hub.py", line 607, in download_url_to_file
    f = tempfile.NamedTemporaryFile(delete=False, dir=dst_dir)
  File "C:\ProgramData\Anaconda3\envs\stable\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\ProgramData\Anaconda3\envs\stable\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\ProgramData\Anaconda3\envs\stable\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'Q:\\test\\sd_new\\models\\3dphoto\\tmp4xy807xx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Q:\test\sd_new\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "Q:\test\sd_new\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "Q:\test\sd_new\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1047, in run_generate
    outputs, mesh_fi = run_depthmap(None, outpath, imageArr, imageNameArr, compute_device, model_type, net_width, net_height, match_size, invert_depth, boost, save_depth, show_depth, show_heat, combine_output, combine_output_axis, gen_stereo, gen_anaglyph, stereo_divergence, stereo_fill, stereo_balance, clipdepth, clipthreshold_far, clipthreshold_near, inpaint, fnExt, vid_ssaa)
  File "Q:\test\sd_new\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 468, in run_depthmap
    mesh_fi = run_3dphoto(device, inpaint_imgs, inpaint_depths, inputnames, outpath, fnExt, vid_ssaa)
  File "Q:\test\sd_new\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 626, in run_3dphoto
    del rgb_model
UnboundLocalError: local variable 'rgb_model' referenced before assignment

Traceback (most recent call last):
  File "Q:\test\sd_new\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "Q:\test\sd_new\venv\lib\site-packages\gradio\blocks.py", line 1016, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "Q:\test\sd_new\venv\lib\site-packages\gradio\blocks.py", line 945, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

**Comment by Darkhitman666** [comment]
so... did u find a fix for this?

**Comment by LilChrisHe** [comment]
Did you find a fix?
