### ISSUE TITLE
TypeError while trying to save settings

### ISSUE THREAD

**Issue by greyphilosophy** [thygate/stable-diffusion-webui-depthmap-script#81]
I just did a git pull and updated all extensions. Not as good a reproduction as a clean install for sure, but here's steps:
Click on Settings 
Click Apply Settings (I don't think you even have to change anything)

Expected: Settings will save
Actual: Settings says Error in red below the apply button and in console is the following:

Traceback (most recent call last):
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1156, in <lambda>
    fn = lambda a, b: a if b > a else b,
TypeError: '>' not supported between instances of 'str' and 'bool'

Fix:
Change line 1156 of depthmap.py to:
fn = lambda a, b: a if b > str(a) else b,

The idea being to make the 'bool' a 'str' so the comparison won't fail. I would put this in as a pull request, except apparently no one else is having this problem? And I don't know python so I have no idea if my fix is even a good idea.

**Comment by thygate** [comment]
a and b are numbers, not booleans, i'm not sure why you're getting that error :\

**Comment by greyphilosophy** [comment]
It's no longer an issue for me. I suspect I just somehow got my local into a bad state. Since it's no longer an issue for me and no one else is reporting I'm going to close the issue.
